import { Archive, Files, Folder, GitBranch, Globe2, PanelRight, Pencil, Pin, PinOff, Terminal } from 'lucide-react';
import type { Task, Workspace } from '../../../contracts/ipc/v1/workspace.js';
import { ActionMenu } from '../../components/ActionMenu.js';
import { Tooltip } from '../../components/ui.js';

export function ConversationHeader({ task, workspace, changesOpen, sourcesOpen, terminalOpen, browserOpen, gitOpen, onToggleChanges, onToggleSources, onToggleTerminal, onToggleBrowser, onToggleGit, onRenameTask, onPinTask, onArchiveTask }: { task?: Task | undefined; workspace?: Workspace | undefined; changesOpen: boolean; sourcesOpen: boolean; terminalOpen: boolean; browserOpen: boolean; gitOpen: boolean; onToggleChanges: () => void; onToggleSources: () => void; onToggleTerminal: () => void; onToggleBrowser: () => void; onToggleGit: () => void; onRenameTask: (task: Task) => void; onPinTask: (pinned: boolean) => void; onArchiveTask: () => void }) {
  const title = task?.title ?? workspace?.name ?? 'Agent Workspace';
  const items = task === undefined ? [] : [{ label: task.pinned ? 'Unpin session' : 'Pin session', icon: task.pinned ? PinOff : Pin, onSelect: () => onPinTask(!task.pinned) }, { label: 'Rename', icon: Pencil, onSelect: () => onRenameTask(task) }, { label: 'Archive session', icon: Archive, tone: 'danger' as const, onSelect: onArchiveTask }];
  return <header className="conversation-header"><div className="task-title"><Folder size={17} /><strong title={title}>{title}</strong>{task ? <ActionMenu ariaLabel={`Session actions for ${title}`} items={items} /> : null}</div><div className="conversation-header-actions"><Tooltip label={gitOpen ? 'Hide Git panel' : 'Show Git panel'}><button type="button" className="icon-button ui-icon-button conversation-panel-toggle" aria-label={gitOpen ? 'Hide Git panel' : 'Show Git panel'} aria-pressed={gitOpen} onClick={onToggleGit}><GitBranch size={17} /></button></Tooltip><Tooltip label={browserOpen ? 'Hide browser' : 'Show browser'}><button type="button" className="icon-button ui-icon-button conversation-panel-toggle" aria-label={browserOpen ? 'Hide browser' : 'Show browser'} aria-pressed={browserOpen} onClick={onToggleBrowser}><Globe2 size={17} /></button></Tooltip><Tooltip label={terminalOpen ? 'Hide terminal' : 'Show terminal'}><button type="button" className="icon-button ui-icon-button conversation-panel-toggle" aria-label={terminalOpen ? 'Hide terminal' : 'Show terminal'} aria-pressed={terminalOpen} onClick={onToggleTerminal}><Terminal size={17} /></button></Tooltip><Tooltip label={sourcesOpen ? 'Hide sources' : 'Show sources'}><button type="button" className="icon-button ui-icon-button conversation-panel-toggle" aria-label={sourcesOpen ? 'Hide sources' : 'Show sources'} aria-pressed={sourcesOpen} onClick={onToggleSources}><Files size={17} /></button></Tooltip><Tooltip label={changesOpen ? 'Hide changed files panel' : 'Show changed files panel'}><button type="button" className="icon-button ui-icon-button conversation-panel-toggle" aria-label={changesOpen ? 'Hide changed files panel' : 'Show changed files panel'} aria-pressed={changesOpen} onClick={onToggleChanges}><PanelRight size={17} /></button></Tooltip></div></header>;
}
