$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'windows-ocr.ps1')

function Fail([string]$Message) { [Console]::Error.WriteLine($Message); exit 1 }
function Output($Value) { $Value | ConvertTo-Json -Depth 12 -Compress; exit 0 }
function Get-RequiredParam($Name) { $value = $request.params.$Name; if ($null -eq $value) { Fail "Missing document parameter: $Name" }; return $value }
function Get-OptionalParam($Name) { return $request.params.$Name }
function Run-External([string]$Name, [string[]]$Arguments) {
  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if ($null -eq $command) { Fail "The document backend requires '$Name', which is not installed or not on PATH." }
  $output = & $command.Source @Arguments 2>&1
  if ($LASTEXITCODE -ne 0) { Fail (($output | Out-String).Trim()) }
  return ($output | Out-String).Trim()
}
function Pdf-PageCount([string]$DocumentPath) { $info = Run-External 'pdfinfo' @($DocumentPath); $match = [regex]::Match($info, '(?m)^Pages:\s*(\d+)'); if (-not $match.Success) { throw 'Unable to determine the PDF page count.' }; return [int]$match.Groups[1].Value }
function Pdf-SelectedPages([string]$DocumentPath) { $pages = $request.params.pages; if ($null -eq $pages -or @($pages).Count -eq 0) { return 0..([Math]::Min((Pdf-PageCount $DocumentPath) - 1, 99)) }; $selected = @($pages | ForEach-Object { [int]$_ } | Where-Object { $_ -ge 0 }); if ($selected.Count -gt 100) { throw 'The PDF page selection exceeds the 100-page limit.' }; return $selected }
function Pdf-ExplicitPages() { $pages = $request.params.pages; if ($null -eq $pages -or @($pages).Count -eq 0) { return $null }; $selected = @($pages | ForEach-Object { if ($_ -isnot [int] -and $_ -isnot [long]) { throw 'PDF pages must be integers.' }; [int]$_ }); if ($selected | Where-Object { $_ -lt 0 }) { throw 'PDF pages must be non-negative.' }; if ($selected.Count -gt 100 -or (@($selected | Sort-Object -Unique).Count -ne $selected.Count)) { throw 'PDF pages must be unique and contain no more than 100 entries.' }; return @($selected | Sort-Object) }
function Read-PdfText([string]$DocumentPath) { $selected = Pdf-ExplicitPages; if ($null -eq $selected) { return Run-External 'pdftotext' @('-layout', $DocumentPath, '-') }; $chunks = @(); foreach ($page in $selected) { $chunks += Run-External 'pdftotext' @('-layout', '-f', ([string]($page + 1)), '-l', ([string]($page + 1)), $DocumentPath, '-') }; return ($chunks -join "`f") }
function Extract-PdfImages([string]$DocumentPath) { $outputDirectory = [string](Get-RequiredParam 'outputPath'); New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null; $selected = Pdf-ExplicitPages; $prefixes = if ($null -eq $selected) { @((Join-Path $outputDirectory 'image')) } else { @($selected | ForEach-Object { Join-Path $outputDirectory ('image-page-' + ([int]$_ + 1).ToString('D4')) }) }; if ($null -eq $selected) { Run-External 'pdfimages' @('-png', $DocumentPath, $prefixes[0]) | Out-Null } else { for ($index = 0; $index -lt $selected.Count; $index++) { Run-External 'pdfimages' @('-png', '-f', ([string]($selected[$index] + 1)), '-l', ([string]($selected[$index] + 1)), $DocumentPath, $prefixes[$index]) | Out-Null } }; $files = if ($null -eq $selected) { @(Get-ChildItem -LiteralPath $outputDirectory -Filter 'image-*' -File | Sort-Object Name | ForEach-Object FullName) } else { @($prefixes | ForEach-Object { $prefix = [IO.Path]::GetFileName($_); Get-ChildItem -LiteralPath $outputDirectory -Filter ($prefix + '-*') -File | Sort-Object Name | ForEach-Object FullName }) }; return @{ format = 'pdf'; outputPath = $outputDirectory; files = $files } }
function Render-Pdf([string]$DocumentPath) { $requested = if ($null -eq $request.params.outputPath) { "$DocumentPath.png" } else { [string]$request.params.outputPath }; if ([string]::IsNullOrWhiteSpace($requested)) { $requested = "$DocumentPath.png" }; $directory = [IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($requested)); New-Item -ItemType Directory -Path $directory -Force | Out-Null; $prefix = [IO.Path]::ChangeExtension($requested, $null); $selected = Pdf-ExplicitPages; $files = @(); if ($null -eq $selected) { Run-External 'pdftoppm' @('-png', $DocumentPath, $prefix) | Out-Null; $files = @(Get-ChildItem -LiteralPath $directory -File | Where-Object { $_.Name.StartsWith([IO.Path]::GetFileName($prefix), [StringComparison]::Ordinal) -and $_.Extension -eq '.png' } | Sort-Object Name | ForEach-Object FullName) } else { for ($index = 0; $index -lt $selected.Count; $index++) { $pagePrefix = if ($selected.Count -eq 1 -and [IO.Path]::GetExtension($requested).ToLowerInvariant() -eq '.png') { $prefix } else { Join-Path $directory ([IO.Path]::GetFileName($prefix) + '-page-' + ([int]$selected[$index] + 1).ToString('D4')) }; Run-External 'pdftoppm' @('-png', '-singlefile', '-f', ([string]($selected[$index] + 1)), '-l', ([string]($selected[$index] + 1)), $DocumentPath, $pagePrefix) | Out-Null; $files += "$pagePrefix.png" } }; return @{ format = 'pdf'; path = $requested; files = $files } }
function Read-PdfBookmarks([string]$DocumentPath) { $dump = Run-External 'pdftk' @($DocumentPath, 'dump_data_utf8'); $items = @(); $current = $null; foreach ($line in ($dump -split "`r?`n")) { if ($line -like 'BookmarkTitle: *') { if ($null -ne $current) { $items += $current }; $current = [ordered]@{ title = $line.Substring(15); level = 1; page = 0 } } elseif ($null -ne $current -and $line -like 'BookmarkLevel: *') { $current.level = [int]$line.Substring(15) } elseif ($null -ne $current -and $line -like 'BookmarkPageNumber: *') { $current.page = [int]$line.Substring(20) - 1 } }; if ($null -ne $current) { $items += $current }; return $items }
function Update-PdfBookmarks([string]$DocumentPath, [string]$Operation) { $bookmark = Get-OptionalParam 'bookmark'; $items = @(Read-PdfBookmarks $DocumentPath); if ($Operation -eq 'add') { if ($null -eq $bookmark.title -or $null -eq $bookmark.page) { throw 'A bookmark title and page are required.' }; $items += [ordered]@{ title = [string]$bookmark.title; level = if ($null -eq $bookmark.level) { 1 } else { [int]$bookmark.level }; page = [int]$bookmark.page } } elseif ($Operation -eq 'update' -or $Operation -eq 'delete') { $index = [int]$bookmark.index; if ($index -lt 0 -or $index -ge $items.Count) { throw 'The bookmark index is invalid.' }; if ($Operation -eq 'delete') { $items = @($items | Where-Object { $_ -ne $items[$index] }) } else { if ($null -ne $bookmark.title) { $items[$index].title = [string]$bookmark.title }; if ($null -ne $bookmark.page) { $items[$index].page = [int]$bookmark.page }; if ($null -ne $bookmark.level) { $items[$index].level = [int]$bookmark.level } } } else { throw "Unsupported PDF bookmark operation '$Operation'." }; $lines = @('InfoBegin', 'InfoKey: ModDate', ('InfoValue: D:' + (Get-Date -Format 'yyyyMMddHHmmss')), 'InfoBegin'); foreach ($item in $items) { $lines += 'BookmarkBegin'; $lines += "BookmarkTitle: $($item.title)"; $lines += "BookmarkLevel: $($item.level)"; $lines += "BookmarkPageNumber: $([int]$item.page + 1)" }; $infoPath = "$DocumentPath.$([guid]::NewGuid()).bookmarks.txt"; $temporary = "$DocumentPath.$([guid]::NewGuid()).pdf"; try { [IO.File]::WriteAllLines($infoPath, $lines, [Text.Encoding]::UTF8); Run-External 'pdftk' @($DocumentPath, 'update_info_utf8', $infoPath, 'output', $temporary) | Out-Null; Move-Item -LiteralPath $temporary -Destination $DocumentPath -Force } finally { Remove-Item -LiteralPath $infoPath -Force -ErrorAction SilentlyContinue; Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue }; return $items }
function Assert-Extension([string]$DocumentPath, [string]$Format) {
  $extension = [IO.Path]::GetExtension($DocumentPath).ToLowerInvariant()
  $allowed = @{ pdf = @('.pdf'); pptx = @('.pptx'); excel = @('.xlsx', '.xls', '.csv'); docs = @('.docx', '.doc', '.txt', '.rtf') }[$Format]
  if ($allowed -notcontains $extension) { Fail "The path extension does not match the $Format document plugin." }
}
function Release-Com([object]$Value) { if ($null -ne $Value -and [Runtime.InteropServices.Marshal]::IsComObject($Value)) { [Runtime.InteropServices.Marshal]::FinalReleaseComObject($Value) | Out-Null } }
function New-Pdf([string]$Target, [string]$Title) {
  $safeTitle = $Title -replace '[()]', ''
  $objects = @('<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>', "<< /Length $($safeTitle.Length + 38) >>`nstream`nBT /F1 18 Tf 72 720 Td ($safeTitle) Tj ET`nendstream", '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
  $text = New-Object Text.StringBuilder; [void]$text.AppendLine('%PDF-1.4'); $offsets = @();
  for ($index = 0; $index -lt $objects.Count; $index++) { $objectNumber = $index + 1; $offsets += $text.Length; [void]$text.AppendLine("$objectNumber 0 obj"); [void]$text.AppendLine($objects[$index]); [void]$text.AppendLine('endobj') }
  $xref = $text.Length; [void]$text.AppendLine('xref'); [void]$text.AppendLine("0 $($objects.Count)"); [void]$text.AppendLine('0000000000 65535 f '); foreach ($offset in $offsets) { [void]$text.AppendLine(('{0:D10} 00000 n ' -f $offset)) }; [void]$text.AppendLine('trailer'); [void]$text.AppendLine("<< /Size $($objects.Count) /Root 1 0 R >>"); [void]$text.AppendLine('startxref'); [void]$text.AppendLine([string]$xref); [void]$text.AppendLine('%%EOF'); [IO.File]::WriteAllText($Target, $text.ToString(), [Text.Encoding]::ASCII)
}
function Office-App([string]$Format) { if ($Format -eq 'docs') { return New-Object -ComObject Word.Application }; if ($Format -eq 'excel') { return New-Object -ComObject Excel.Application }; return New-Object -ComObject PowerPoint.Application }
function Office-Open([string]$Format, [string]$DocumentPath, [object]$App) {
  if ($Format -eq 'docs') { return $App.Documents.Open($DocumentPath, $false, $false) }
  if ($Format -eq 'excel') { return $App.Workbooks.Open($DocumentPath) }
  return $App.Presentations.Open($DocumentPath, $true, $false, $false)
}
function Office-Close([string]$Format, [object]$Document, [object]$App) {
  if ($null -ne $Document) { if ($Format -eq 'docs') { $Document.Close($false) } elseif ($Format -eq 'excel') { $Document.Close($false) } else { $Document.Close() } }
  if ($null -ne $App) { $App.Quit() }; Release-Com $Document; Release-Com $App
}
function Office-Sheet([object]$Document) { if ($null -eq (Get-OptionalParam 'sheet')) { return $Document.Worksheets.Item(1) }; return $Document.Worksheets.Item([string](Get-OptionalParam 'sheet')) }
function Office-Slide([object]$Document) { return $Document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1) }
function Office-Range([object]$Document) { return $Document.Range([int](Get-RequiredParam 'start'), [int](Get-RequiredParam 'end')) }
function Escape-CsvValue([object]$Value) { $text = if ($null -eq $Value -or $Value -is [DBNull]) { '' } else { [string]$Value }; if ($text.Contains(',') -or $text.Contains('"') -or $text.Contains("`r") -or $text.Contains("`n")) { return '"' + $text.Replace('"', '""') + '"' }; return $text }
function Export-ExcelCsv([object]$Sheet, [string]$OutputPath) { $range = if ($null -eq $request.params.range) { $Sheet.UsedRange } else { $Sheet.Range([string](Get-RequiredParam 'range')) }; New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($OutputPath))) -Force | Out-Null; $values = $range.Value2; $lines = New-Object 'System.Collections.Generic.List[string]'; if ($values -is [Array] -and $values.Rank -ge 2) { for ($row = 0; $row -lt $values.GetLength(0); $row++) { $cells = @(); for ($column = 0; $column -lt $values.GetLength(1); $column++) { $cells += Escape-CsvValue $values[$row + 1, $column + 1] }; $lines.Add(($cells -join ',')) } } else { $lines.Add((Escape-CsvValue $values)) }; [IO.File]::WriteAllLines($OutputPath, $lines, [Text.UTF8Encoding]::new($false)); return @{ path = $OutputPath; exported = $true; sheet = [string]$Sheet.Name; range = if ($null -eq $request.params.range) { [string]$range.Address() } else { [string]$request.params.range } } }
function Pptx-SelectedSlides([object]$Document) { $pages = $request.params.pages; if ($null -eq $pages -or @($pages).Count -eq 0) { return @(1..$Document.Slides.Count) }; $selected = @($pages | ForEach-Object { $value = [int]$_; if ($value -lt 0 -or $value -ge $Document.Slides.Count) { throw 'Presentation pages contain an invalid slide index.' }; $value + 1 }); if ((@($selected | Sort-Object -Unique).Count -ne $selected.Count)) { throw 'Presentation pages must be unique.' }; return $selected }
function Replace-PptxText([object]$Document) { $findText = [string](Get-RequiredParam 'find'); $replaceText = [string](Get-RequiredParam 'replace'); $count = 0; $selected = Pptx-SelectedSlides $Document; foreach ($slideIndex in $selected) { foreach ($shape in $Document.Slides.Item($slideIndex).Shapes) { if ($shape.HasTextFrame -and $shape.TextFrame.HasText) { $range = $shape.TextFrame.TextRange; $before = [string]$range.Text; $after = $before.Replace($findText, $replaceText); if ($before -ne $after) { $range.Text = $after; $count++ } } } }; $Document.Save(); return @{ saved = $true; operation = 'findReplace'; replacements = $count; pages = @($selected | ForEach-Object { $_ - 1 }) } }
function Read-DocsExtended([object]$document, [string]$operation) {
  if ($operation -eq 'inspectStructure') { $paragraphs = @(); foreach ($paragraph in $document.Paragraphs) { if ($paragraphs.Count -ge 1000) { break }; $paragraphs += [ordered]@{ index = $paragraphs.Count; text = Bound-Text ([string]$paragraph.Range.Text.Trim()); style = [string]$paragraph.Style; outlineLevel = [int]$paragraph.OutlineLevel } }; $tables = @(); for ($i = 1; $i -le $document.Tables.Count; $i++) { $table = $document.Tables.Item($i); $tables += [ordered]@{ index = $i - 1; rows = $table.Rows.Count; columns = $table.Columns.Count } }; $sections = @(); for ($i = 1; $i -le $document.Sections.Count; $i++) { $sections += [ordered]@{ index = $i - 1; start = $document.Sections.Item($i).Range.Start; end = $document.Sections.Item($i).Range.End } }; Output @{ operation = $operation; paragraphs = $paragraphs; tables = $tables; sections = $sections } }
  if ($operation -eq 'manageBookmarks' -and [string]$request.params.operation -eq 'list') { $items = @(); foreach ($bookmark in $document.Bookmarks) { $items += [ordered]@{ name = [string]$bookmark.Name; start = [int]$bookmark.Range.Start; end = [int]$bookmark.Range.End; text = Bound-Text ([string]$bookmark.Range.Text) } }; Output @{ operation = 'list'; bookmarks = $items } }
  if ($operation -eq 'manageHyperlinks' -and [string]$request.params.operation -eq 'list') { $items = @(); foreach ($link in $document.Hyperlinks) { $items += [ordered]@{ address = [string]$link.Address; subAddress = [string]$link.SubAddress; text = Bound-Text ([string]$link.Range.Text); start = [int]$link.Range.Start; end = [int]$link.Range.End } }; Output @{ operation = 'list'; hyperlinks = $items } }
  if ($operation -eq 'manageLists' -and [string]$request.params.operation -eq 'list') { $items = @(); foreach ($paragraph in $document.Paragraphs) { if ($items.Count -ge 1000) { break }; if ([int]$paragraph.Range.ListFormat.ListType -ne 0) { $items += [ordered]@{ text = Bound-Text ([string]$paragraph.Range.Text.Trim()); level = [int]$paragraph.Range.ListFormat.ListLevelNumber; type = [int]$paragraph.Range.ListFormat.ListType } } }; Output @{ operation = 'list'; items = $items } }
  if ($operation -eq 'manageFootnotes' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($i = 1; $i -le $document.Footnotes.Count; $i++) { $note = $document.Footnotes.Item($i); $items += [ordered]@{ index = $i - 1; text = Bound-Text ([string]$note.Range.Text); reference = [int]$note.Reference.Start } }; Output @{ operation = 'list'; footnotes = $items } }
  Fail "The docs read operation '$operation' is not supported by the installed Office backend."
}
function Read-ExcelExtended([object]$document, [string]$operation) {
  $sheet = Office-Sheet $document
  if ($operation -eq 'readFormulas') { $range = $sheet.Range([string](Get-RequiredParam 'range')); Output @{ operation = $operation; sheet = $sheet.Name; range = $range.Address(); formulas = $range.Formula; values = $range.Value2 } }
  if ($operation -eq 'manageConditionalFormatting' -and [string]$request.params.operation -eq 'list') { $range = $sheet.Range([string](Get-RequiredParam 'range')); $items = @(); for ($i = 1; $i -le $range.FormatConditions.Count; $i++) { $rule = $range.FormatConditions.Item($i); $items += [ordered]@{ index = $i - 1; type = [int]$rule.Type; operator = [int]$rule.Operator; formula1 = [string]$rule.Formula1; formula2 = [string]$rule.Formula2 } }; Output @{ operation = 'list'; sheet = $sheet.Name; range = $range.Address(); rules = $items } }
  if ($operation -eq 'manageSheetView' -and [string]$request.params.operation -eq 'list') { Output @{ operation = 'list'; sheet = $sheet.Name; visible = [int]$sheet.Visible; usedRange = $sheet.UsedRange.Address(); freezePanes = [bool]$document.Application.ActiveWindow.FreezePanes; zoom = [int]$document.Application.ActiveWindow.Zoom } }
  if ($operation -eq 'manageComments' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($i = 1; $i -le $sheet.Comments.Count; $i++) { $comment = $sheet.Comments.Item($i); $items += [ordered]@{ index = $i - 1; address = [string]$comment.Parent.Address(); text = Bound-Text ([string]$comment.Text()); author = [string]$comment.Author } }; Output @{ operation = 'list'; sheet = $sheet.Name; comments = $items } }
  if ($operation -eq 'manageProtection' -and [string]$request.params.operation -eq 'status') { $kind = if ($null -eq $request.params.kind) { 'worksheet' } else { [string]$request.params.kind }; $protected = if ($kind -eq 'workbook') { [bool]$document.ProtectStructure } else { [bool]$sheet.ProtectContents }; Output @{ operation = 'status'; kind = $kind; protected = $protected; sheet = $sheet.Name } }
  Fail "The excel read operation '$operation' is not supported by the installed Office backend."
}
function Read-PptxExtended([object]$document, [string]$operation) {
  if ($operation -eq 'extractText') { $slides = if ($null -eq $request.params.pages) { 1..$document.Slides.Count } else { @($request.params.pages | ForEach-Object { [int]$_ + 1 }) }; $items = @(); foreach ($number in $slides) { $slide = $document.Slides.Item($number); $text = New-Object Text.StringBuilder; foreach ($shape in $slide.Shapes) { if ($shape.HasTextFrame -and $shape.TextFrame.HasText) { [void]$text.AppendLine([string]$shape.TextFrame.TextRange.Text) } }; $items += [ordered]@{ slide = $number - 1; text = Bound-Text ($text.ToString().Trim()) } }; Output @{ operation = $operation; slides = $items } }
  if ($operation -eq 'manageMedia' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($s = 1; $s -le $document.Slides.Count; $s++) { foreach ($shape in $document.Slides.Item($s).Shapes) { if ([int]$shape.Type -in @(13, 16)) { $items += [ordered]@{ slide = $s - 1; elementId = [string]$shape.Name; type = [int]$shape.Type; left = $shape.Left; top = $shape.Top; width = $shape.Width; height = $shape.Height } } } }; Output @{ operation = 'list'; media = $items } }
  if ($operation -eq 'manageHyperlinks' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($s = 1; $s -le $document.Slides.Count; $s++) { foreach ($shape in $document.Slides.Item($s).Shapes) { $link = $shape.ActionSettings(1).Hyperlink; if ($null -ne $link -and (-not [string]::IsNullOrWhiteSpace([string]$link.Address) -or -not [string]::IsNullOrWhiteSpace([string]$link.SubAddress))) { $items += [ordered]@{ slide = $s - 1; elementId = [string]$shape.Name; address = [string]$link.Address; subAddress = [string]$link.SubAddress } } } }; Output @{ operation = 'list'; hyperlinks = $items } }
  if ($operation -eq 'manageTransitions' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($s = 1; $s -le $document.Slides.Count; $s++) { $transition = $document.Slides.Item($s).SlideShowTransition; $items += [ordered]@{ slide = $s - 1; entryEffect = [int]$transition.EntryEffect; advanceOnClick = [bool]$transition.AdvanceOnClick; advanceTime = [double]$transition.AdvanceTime } }; Output @{ operation = 'list'; transitions = $items } }
  if ($operation -eq 'manageLayouts' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($i = 1; $i -le $document.SlideMaster.CustomLayouts.Count; $i++) { $layout = $document.SlideMaster.CustomLayouts.Item($i); $items += [ordered]@{ index = $i - 1; name = [string]$layout.Name; type = [int]$layout.Type } }; Output @{ operation = 'list'; layouts = $items } }
  Fail "The pptx read operation '$operation' is not supported by the installed PowerPoint backend."
}
function Read-Office([string]$Format, [string]$DocumentPath, [string]$Operation) {
  $app = $null; $document = $null
  try {
    $app = Office-App $Format; $app.Visible = $false; $document = Office-Open $Format $DocumentPath $app
    if ($Format -eq 'docs' -and $Operation -in @('inspectStructure', 'manageBookmarks', 'manageHyperlinks', 'manageLists', 'manageFootnotes')) { Read-DocsExtended $document $Operation }
    if ($Format -eq 'excel' -and $Operation -in @('readFormulas', 'manageConditionalFormatting', 'manageSheetView', 'manageComments', 'manageProtection')) { Read-ExcelExtended $document $Operation }
    if ($Format -eq 'pptx' -and $Operation -in @('extractText', 'manageMedia', 'manageHyperlinks', 'manageTransitions', 'manageLayouts')) { Read-PptxExtended $document $Operation }
    if ($Format -eq 'docs' -and $Operation -eq 'readContent') { Output @{ content = [string]$document.Content.Text; format = 'docs' } }
    if ($Format -eq 'docs' -and $Operation -eq 'manageTable' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($index = 1; $index -le $document.Tables.Count; $index++) { $table = $document.Tables.Item($index); $items += [ordered]@{ index = $index - 1; rows = $table.Rows.Count; columns = $table.Columns.Count } }; Output @{ operation = 'list'; tables = $items } }
    if ($Format -eq 'docs' -and $Operation -eq 'manageTable' -and [string]$request.params.operation -eq 'read') { $table = $document.Tables.Item(([int](Get-RequiredParam 'index')) + 1); $rows = @(); for ($row = 1; $row -le $table.Rows.Count; $row++) { $cells = @(); for ($column = 1; $column -le $table.Columns.Count; $column++) { $cells += [string]$table.Cell($row, $column).Range.Text.Trim([char]13, [char]7) }; $rows += ,$cells }; Output @{ operation = 'read'; index = [int]$request.params.index; rows = $rows } }
    if ($Format -eq 'docs' -and $Operation -eq 'manageImage' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($index = 1; $index -le $document.InlineShapes.Count; $index++) { $image = $document.InlineShapes.Item($index); $items += [ordered]@{ index = $index - 1; width = $image.Width; height = $image.Height; altText = [string]$image.AlternativeText } }; Output @{ operation = 'list'; images = $items } }
    if ($Format -eq 'docs' -and $Operation -eq 'updateFields') { $updated = $document.Fields.Update(); Output @{ updated = [int]$updated } }
    if ($Format -eq 'excel' -and $Operation -eq 'readRange') { $sheet = if ($null -eq (Get-OptionalParam 'sheet')) { $document.Worksheets.Item(1) } else { $document.Worksheets.Item([string](Get-OptionalParam 'sheet')) }; $range = $sheet.Range([string](Get-RequiredParam 'range')); Output @{ sheet = $sheet.Name; range = $range.Address(); values = $range.Value2 } }
    if ($Format -eq 'excel' -and $Operation -eq 'find') { $query = [string](Get-RequiredParam 'query'); $matches = @(); for ($sheetIndex = 1; $sheetIndex -le $document.Worksheets.Count -and $matches.Count -lt 500; $sheetIndex++) { $sheet = $document.Worksheets.Item($sheetIndex); $used = $sheet.UsedRange; for ($row = 1; $row -le $used.Rows.Count -and $matches.Count -lt 500; $row++) { for ($column = 1; $column -le $used.Columns.Count -and $matches.Count -lt 500; $column++) { $cell = $used.Cells.Item($row, $column); if ([string]$cell.Text -like "*$query*") { $matches += [ordered]@{ sheet = $sheet.Name; address = $cell.Address(); value = [string]$cell.Text } } } } }; Output @{ query = $query; matches = $matches; truncated = $matches.Count -ge 500 } }
    if ($Format -eq 'excel' -and $Operation -eq 'manageNamedRange' -and [string]$request.params.operation -eq 'list') { $items = @(); for ($index = 1; $index -le $document.Names.Count; $index++) { $named = $document.Names.Item($index); $items += [ordered]@{ name = [string]$named.Name; formula = [string]$named.RefersTo } }; Output @{ operation = 'list'; names = $items } }
    if ($Format -eq 'excel' -and $Operation -eq 'managePivotTable' -and [string]$request.params.operation -eq 'list') { $sheet = if ($null -eq (Get-OptionalParam 'sheet')) { $document.Worksheets.Item(1) } else { $document.Worksheets.Item([string](Get-OptionalParam 'sheet')) }; $items = @(); for ($index = 1; $index -le $sheet.PivotTables().Count; $index++) { $pivot = $sheet.PivotTables().Item($index); $items += [ordered]@{ name = [string]$pivot.Name; address = [string]$pivot.TableRange2.Address() } }; Output @{ operation = 'list'; pivots = $items } }
    if ($Format -eq 'pptx' -and $Operation -eq 'readSlide') { $slide = $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1); $items = @(); foreach ($shape in $slide.Shapes) { if ($shape.HasTextFrame -and $shape.TextFrame.HasText) { $items += @{ name = $shape.Name; text = [string]$shape.TextFrame.TextRange.Text } } }; Output @{ slide = ([int](Get-RequiredParam 'slide')); elements = $items } }
    Fail "The $Format read operation '$Operation' is not supported by the installed Office backend."
  } finally { Office-Close $Format $document $app }
}
function Read-OfficeExtended([string]$Format, [string]$DocumentPath, [string]$Operation) {
  $app = $null; $document = $null
  try {
    $app = Office-App $Format; $app.Visible = $false; $document = Office-Open $Format $DocumentPath $app
    if ($Format -eq 'docs' -and $Operation -eq 'manageRevisions') { Output @{ operation = 'status'; tracked = [bool]$document.TrackRevisions } }
    if ($Format -eq 'docs' -and $Operation -eq 'manageComments') { $items = @(); foreach ($comment in $document.Comments) { $items += [ordered]@{ index = $items.Count; author = [string]$comment.Author; text = Bound-Text ([string]$comment.Range.Text); start = [int]$comment.Scope.Start; end = [int]$comment.Scope.End } }; Output @{ operation = 'list'; comments = $items } }
    if ($Format -eq 'excel' -and $Operation -eq 'manageTable') { $sheet = Office-Sheet $document; $items = @(); foreach ($table in $sheet.ListObjects) { $items += [ordered]@{ name = [string]$table.Name; range = [string]$table.Range.Address() } }; Output @{ operation = 'list'; tables = $items } }
    if ($Format -eq 'excel' -and $Operation -eq 'manageChart') { $sheet = Office-Sheet $document; $items = @(); foreach ($chart in $sheet.ChartObjects()) { $items += [ordered]@{ name = [string]$chart.Name; left = $chart.Left; top = $chart.Top; width = $chart.Width; height = $chart.Height } }; Output @{ operation = 'list'; charts = $items } }
    if ($Format -eq 'excel' -and $Operation -eq 'filterRange') { $sheet = Office-Sheet $document; Output @{ operation = 'list'; sheet = $sheet.Name; filtered = [bool]$sheet.FilterMode; range = if ($null -eq $request.params.range) { $null } else { [string]$request.params.range } } }
    Fail "The $Format extended read operation '$Operation' is not supported by the installed Office backend."
  } finally { Office-Close $Format $document $app }
}

function Export-OfficePdf([string]$Format, [object]$Document, [string]$OutputPath) {
  if ([string]::IsNullOrWhiteSpace($OutputPath)) { throw 'An outputPath is required for document PDF export.' }
  New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($OutputPath))) -Force | Out-Null
  if ($Format -eq 'docs') { $Document.ExportAsFixedFormat($OutputPath, 17) }
  elseif ($Format -eq 'excel') { $Document.ExportAsFixedFormat(0, $OutputPath) }
  else { $Document.SaveAs($OutputPath, 32) }
  return $OutputPath
}

function Render-OfficeDocument([string]$Format, [object]$Document, [string]$DocumentPath) {
  $requested = if ($null -eq $request.params.outputPath) { $null } else { [string]$request.params.outputPath }
  $root = if ([string]::IsNullOrWhiteSpace($requested)) { Join-Path ([IO.Path]::GetDirectoryName($DocumentPath)) ([IO.Path]::GetFileNameWithoutExtension($DocumentPath) + '.render') } elseif ([IO.Path]::GetExtension($requested).ToLowerInvariant() -eq '.pdf') { [IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($requested)) } else { $requested }
  New-Item -ItemType Directory -Path $root -Force | Out-Null
  $pdf = if ($null -ne $requested -and [IO.Path]::GetExtension($requested).ToLowerInvariant() -eq '.pdf') { $requested } else { Join-Path $root ([IO.Path]::GetFileNameWithoutExtension($DocumentPath) + '.pdf') }
  Export-OfficePdf $Format $Document $pdf | Out-Null
  $base = [IO.Path]::GetFileNameWithoutExtension($DocumentPath)
  $prefix = Join-Path $root $base
  $selected = Pdf-ExplicitPages
  $files = @()
  if ($null -eq $selected) {
    Run-External 'pdftoppm' @('-png', $pdf, $prefix) | Out-Null
    $files = @(Get-ChildItem -LiteralPath $root -File | Where-Object { $_.Name.StartsWith($base, [StringComparison]::Ordinal) -and $_.Extension -eq '.png' } | Sort-Object Name | ForEach-Object FullName)
  } else {
    for ($index = 0; $index -lt $selected.Count; $index++) {
      $pagePrefix = Join-Path $root ($base + '-page-' + ([int]$selected[$index] + 1).ToString('D4'))
      Run-External 'pdftoppm' @('-png', '-singlefile', '-f', ([string]($selected[$index] + 1)), '-l', ([string]($selected[$index] + 1)), $pdf, $pagePrefix) | Out-Null
      $files += "$pagePrefix.png"
    }
  }
  return @{ path = $root; pdf = $pdf; files = $files }
}

function Write-OfficeExtended([string]$Format, [string]$DocumentPath, [string]$Operation) {
  $app = $null; $document = $null
  try {
    $app = Office-App $Format; $app.Visible = $false; $document = Office-Open $Format $DocumentPath $app
    if ($Format -eq 'docs' -and $Operation -eq 'setSection') { $section = $document.Sections.Item(1); $options = Get-OptionalParam 'options'; if ($null -ne $options.marginLeft) { $section.PageSetup.LeftMargin = [float]$options.marginLeft }; if ($null -ne $options.marginRight) { $section.PageSetup.RightMargin = [float]$options.marginRight }; if ($null -ne $options.marginTop) { $section.PageSetup.TopMargin = [float]$options.marginTop }; if ($null -ne $options.marginBottom) { $section.PageSetup.BottomMargin = [float]$options.marginBottom }; $document.Save(); Output @{ saved = $true; operation = $Operation } }
    if ($Format -eq 'docs' -and $Operation -eq 'manageRevisions') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'enable' -or $mode -eq 'track') { $document.TrackRevisions = $true } elseif ($mode -eq 'disable' -or $mode -eq 'untrack') { $document.TrackRevisions = $false } else { Fail "Unsupported revision operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; tracked = [bool]$document.TrackRevisions } }
    if ($Format -eq 'docs' -and $Operation -eq 'manageComments') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'add') { $range = Office-Range $document; $comment = $document.Comments.Add($range, [string](Get-RequiredParam 'text')); $document.Save(); Output @{ saved = $true; operation = $mode; index = $document.Comments.Count - 1 } }; $index = [int](Get-RequiredParam 'index') + 1; $comment = $document.Comments.Item($index); if ($mode -eq 'update') { $comment.Range.Text = [string](Get-RequiredParam 'text') } elseif ($mode -eq 'delete') { $comment.Delete() } else { Fail "Unsupported comment operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; index = $index - 1 } }
    if ($Format -eq 'docs' -and ($Operation -eq 'exportPdf' -or $Operation -eq 'render')) { if ($Operation -eq 'exportPdf') { $output = Export-OfficePdf $Format $document ([string](Get-RequiredParam 'outputPath')); Output @{ path = $output; exported = $true } }; Output (Render-OfficeDocument $Format $document $DocumentPath) }
    if ($Format -eq 'excel') {
      $sheet = Office-Sheet $document
      if ($Operation -eq 'updateSheet') { $old = $sheet.Name; $sheet.Name = [string](Get-RequiredParam 'sheetName'); $document.Save(); Output @{ saved = $true; operation = $Operation; sheet = $old; renamedTo = $sheet.Name } }
      if ($Operation -eq 'manageTable') { $mode = [string](Get-RequiredParam 'operation'); $range = $sheet.Range([string](Get-RequiredParam 'range')); if ($mode -eq 'create') { $table = $sheet.ListObjects.Add(1, $range, $null, 1); if ($null -ne $request.params.tableName) { $table.Name = [string]$request.params.tableName }; $document.Save(); Output @{ saved = $true; operation = $mode; name = [string]$table.Name } }; $table = $sheet.ListObjects.Item([string](Get-RequiredParam 'tableName')); if ($mode -eq 'update') { $table.Resize($range) } elseif ($mode -eq 'delete') { $table.Unlist() } else { Fail "Unsupported table operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; name = [string]$table.Name } }
      if ($Operation -eq 'manageChart') { $mode = [string](Get-RequiredParam 'operation'); $options = Get-OptionalParam 'options'; if ($mode -eq 'create') { $left = if ($null -eq $options.left) { 0 } else { [float]$options.left }; $top = if ($null -eq $options.top) { 0 } else { [float]$options.top }; $width = if ($null -eq $options.width) { 480 } else { [float]$options.width }; $height = if ($null -eq $options.height) { 300 } else { [float]$options.height }; $chart = $sheet.ChartObjects().Add($left, $top, $width, $height); $chart.Name = [string](Get-RequiredParam 'name'); $chart.Chart.SetSourceData($sheet.Range([string](Get-RequiredParam 'sourceRange'))); if ($null -ne $options.title) { $chart.Chart.HasTitle = $true; $chart.Chart.ChartTitle.Text = [string]$options.title } } else { $chart = $sheet.ChartObjects().Item([string](Get-RequiredParam 'name')); if ($mode -eq 'update') { if ($null -ne $options.title) { $chart.Chart.HasTitle = $true; $chart.Chart.ChartTitle.Text = [string]$options.title } } elseif ($mode -eq 'delete') { $chart.Delete() } else { Fail "Unsupported chart operation '$mode'." } }; $document.Save(); Output @{ saved = $true; operation = $mode; name = [string]$request.params.name } }
      if ($Operation -eq 'filterRange') { $mode = [string](Get-RequiredParam 'operation'); $range = $sheet.Range([string](Get-RequiredParam 'range')); if ($mode -eq 'set') { $field = if ($null -eq $request.params.options.field) { 1 } else { [int]$request.params.options.field }; $criteria = if ($null -eq $request.params.options.value) { '*' } else { [string]$request.params.options.value }; $range.AutoFilter($field, $criteria) } elseif ($mode -eq 'clear') { $sheet.AutoFilterMode = $false } else { Fail "Unsupported filter operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; range = $range.Address() } }
      if ($Operation -eq 'formatRange') { $range = $sheet.Range([string](Get-RequiredParam 'range')); $options = Get-OptionalParam 'options'; if ($null -ne $options.backgroundColor) { $range.Interior.Color = [int]$options.backgroundColor }; if ($null -ne $options.fontColor) { $range.Font.Color = [int]$options.fontColor }; if ($null -ne $options.bold) { $range.Font.Bold = [bool]$options.bold }; if ($null -ne $options.fontSize) { $range.Font.Size = [float]$options.fontSize }; $document.Save(); Output @{ saved = $true; operation = $Operation; range = $range.Address() } }
      if ($Operation -eq 'sortRange') { $range = $sheet.Range([string](Get-RequiredParam 'range')); $index = if ($null -eq $request.params.index) { 1 } else { [int]$request.params.index + 1 }; $ascending = if ($null -eq $request.params.ascending) { $true } else { [bool]$request.params.ascending }; $range.Sort($range.Columns.Item($index), $(if ($ascending) { 1 } else { 2 })) | Out-Null; $document.Save(); Output @{ saved = $true; operation = $Operation; range = $range.Address() } }
      if ($Operation -eq 'editRows' -or $Operation -eq 'editColumns') { $index = [int](Get-RequiredParam 'index') + 1; $count = if ($null -eq $request.params.count) { 1 } else { [Math]::Max([int]$request.params.count, 1) }; $mode = [string](Get-RequiredParam 'operation'); for ($i = 0; $i -lt $count; $i++) { $target = if ($Operation -eq 'editRows') { $sheet.Rows.Item($index) } else { $sheet.Columns.Item($index) }; if ($mode -eq 'insert') { $target.Insert() } elseif ($mode -eq 'delete') { $target.Delete() } else { Fail "Unsupported row or column operation '$mode'." } }; $document.Save(); Output @{ saved = $true; operation = $Operation; mode = $mode; index = $index - 1; count = $count } }
      if ($Operation -eq 'importCsv') { $sourceApp = New-Object -ComObject Excel.Application; $source = $null; try { $sourceApp.Visible = $false; $source = $sourceApp.Workbooks.Open([string](Get-RequiredParam 'sourcePath')); $source.Worksheets.Item(1).UsedRange.Copy($sheet.Range('A1')) | Out-Null; $document.Save(); Output @{ saved = $true; operation = $Operation; imported = $true } } finally { if ($null -ne $source) { $source.Close($false) }; if ($null -ne $sourceApp) { $sourceApp.Quit() }; Release-Com $source; Release-Com $sourceApp } }
      if ($Operation -eq 'exportCsv') { $output = [string](Get-RequiredParam 'outputPath'); Output (Export-ExcelCsv $sheet $output) }
      if ($Operation -eq 'exportPdf' -or $Operation -eq 'render') { if ($Operation -eq 'exportPdf') { $output = Export-OfficePdf $Format $document ([string](Get-RequiredParam 'outputPath')); Output @{ path = $output; exported = $true } }; Output (Render-OfficeDocument $Format $document $DocumentPath) }
    }
    if ($Format -eq 'pptx') {
      if ($Operation -eq 'reorderSlides') { $order = @($request.params.pages | ForEach-Object { [int]$_ }); if ($order.Count -ne $document.Slides.Count -or ((@($order | Sort-Object) -join ',') -ne ((0..($document.Slides.Count - 1)) -join ','))) { Fail 'pptx.reorderSlides requires a complete slide permutation.' }; $original = @(1..$document.Slides.Count | ForEach-Object { $document.Slides.Item($_) }); for ($target = 0; $target -lt $order.Count; $target++) { $original[$order[$target]].MoveTo($target + 1) }; $document.Save(); Output @{ saved = $true; operation = $Operation; pages = $order } }
      if ($Operation -eq 'setTheme') { $options = Get-OptionalParam 'options'; foreach ($slide in $document.Slides) { if ($null -ne $options.backgroundColor) { $slide.FollowMasterBackground = $false; $slide.Background.Fill.Solid(); $slide.Background.Fill.ForeColor.RGB = [int]$options.backgroundColor }; if ($null -ne $options.fontName) { foreach ($shape in $slide.Shapes) { if ($shape.HasTextFrame) { $shape.TextFrame.TextRange.Font.Name = [string]$options.fontName } } } }; $document.Save(); Output @{ saved = $true; operation = $Operation; updated = $true } }
      if ($Operation -eq 'updateSlide') { $slide = Office-Slide $document; if ($null -ne $request.params.name) { $slide.Name = [string]$request.params.name }; $document.Save(); Output @{ saved = $true; operation = $Operation; slide = $slide.SlideIndex - 1 } }
      if ($Operation -eq 'addElement') { $slide = Office-Slide $document; $options = Get-OptionalParam 'options'; $shape = $slide.Shapes.AddTextbox(1, $(if ($null -eq $options.left) { 0 } else { [float]$options.left }), $(if ($null -eq $options.top) { 0 } else { [float]$options.top }), $(if ($null -eq $options.width) { 320 } else { [float]$options.width }), $(if ($null -eq $options.height) { 0 } else { [float]$options.height })); $shape.TextFrame.TextRange.Text = [string]$request.params.text; if ($null -ne $request.params.elementId) { $shape.Name = [string]$request.params.elementId }; $document.Save(); Output @{ saved = $true; operation = $Operation; elementId = [string]$shape.Name } }
      if ($Operation -eq 'updateElement' -or $Operation -eq 'deleteElement') { $slide = Office-Slide $document; $shape = $slide.Shapes.Item([string](Get-RequiredParam 'elementId')); if ($Operation -eq 'deleteElement') { $shape.Delete() } else { $options = Get-OptionalParam 'options'; if ($null -ne $request.params.text) { $shape.TextFrame.TextRange.Text = [string]$request.params.text }; if ($null -ne $options.left) { $shape.Left = [float]$options.left }; if ($null -ne $options.top) { $shape.Top = [float]$options.top }; if ($null -ne $options.width) { $shape.Width = [float]$options.width }; if ($null -ne $options.height) { $shape.Height = [float]$options.height } }; $document.Save(); Output @{ saved = $true; operation = $Operation; elementId = [string]$request.params.elementId } }
      if ($Operation -eq 'exportPdf' -or $Operation -eq 'render') { if ($Operation -eq 'exportPdf') { $output = Export-OfficePdf $Format $document ([string](Get-RequiredParam 'outputPath')); Output @{ path = $output; exported = $true } }; Output (Render-OfficeDocument $Format $document $DocumentPath) }
    }
  } finally { Office-Close $Format $document $app }
}

function Write-Office([string]$Format, [string]$DocumentPath, [string]$Operation) {
  $app = $null; $document = $null
  try {
    $app = Office-App $Format; $app.Visible = $false; $document = Office-Open $Format $DocumentPath $app
    if ($Format -eq 'docs') {
      $content = $document.Content
      if ($Operation -eq 'insertContent') { $content.InsertAfter([string](Get-RequiredParam 'content')) }
      elseif ($Operation -eq 'updateContent' -or $Operation -eq 'deleteContent') { $start = [int](Get-RequiredParam 'start'); $end = [int](Get-RequiredParam 'end'); $range = $document.Range($start, $end); $range.Text = if ($Operation -eq 'deleteContent') { '' } else { [string](Get-RequiredParam 'content') } }
      elseif ($Operation -eq 'findReplace') { $find = $content.Find; $find.Text = [string](Get-RequiredParam 'find'); $find.Replacement.Text = [string](Get-RequiredParam 'replace'); $find.Execute($null, $false, $false, $false, $false, $false, $true, 1, $false, [string](Get-RequiredParam 'replace'), 2) | Out-Null }
      elseif ($Operation -eq 'setStyles') { $content.Style = [string](Get-RequiredParam 'style') }
      elseif ($Operation -eq 'setHeaderFooter') { $section = $document.Sections.Item(1); $section.Headers.Item(1).Range.Text = [string](Get-RequiredParam 'content') }
      elseif ($Operation -eq 'manageTable') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'create') { $options = Get-OptionalParam 'options'; $rows = if ($null -eq $options.rows) { 2 } else { [int]$options.rows }; $columns = if ($null -eq $options.columns) { 2 } else { [int]$options.columns }; $table = $document.Tables.Add($document.Range($document.Content.End - 1, $document.Content.End - 1), $rows, $columns); $document.Save(); Output @{ saved = $true; operation = $mode; index = $document.Tables.Count - 1 } } elseif ($mode -eq 'update') { $table = $document.Tables.Item(([int](Get-RequiredParam 'index')) + 1); $values = Get-RequiredParam 'values'; for ($row = 0; $row -lt $values.Count -and $row -lt $table.Rows.Count; $row++) { for ($column = 0; $column -lt $values[$row].Count -and $column -lt $table.Columns.Count; $column++) { $table.Cell($row + 1, $column + 1).Range.Text = [string]$values[$row][$column] } }; $document.Save(); Output @{ saved = $true; operation = $mode } } elseif ($mode -eq 'delete') { $table = $document.Tables.Item(([int](Get-RequiredParam 'index')) + 1); $table.Delete(); $document.Save(); Output @{ saved = $true; operation = $mode } } else { Fail "Unsupported document table operation '$mode'." } }
      elseif ($Operation -eq 'manageImage') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'insert') { $range = $document.Range($document.Content.End - 1, $document.Content.End - 1); $image = $document.InlineShapes.AddPicture([string](Get-RequiredParam 'imagePath'), $false, $true, $range); $document.Save(); Output @{ saved = $true; operation = $mode; index = $document.InlineShapes.Count - 1 } } elseif ($mode -eq 'update') { $image = $document.InlineShapes.Item(([int](Get-RequiredParam 'index')) + 1); if ($null -ne $request.params.width) { $image.Width = [float]$request.params.width }; if ($null -ne $request.params.height) { $image.Height = [float]$request.params.height }; if ($null -ne $request.params.altText) { $image.AlternativeText = [string]$request.params.altText }; $document.Save(); Output @{ saved = $true; operation = $mode } } elseif ($mode -eq 'delete') { $document.InlineShapes.Item(([int](Get-RequiredParam 'index')) + 1).Delete(); $document.Save(); Output @{ saved = $true; operation = $mode } } else { Fail "Unsupported document image operation '$mode'." } }
      elseif ($Operation -eq 'fillTemplate') { $values = Get-RequiredParam 'values'; $filled = 0; for ($index = 1; $index -le $document.ContentControls.Count; $index++) { $control = $document.ContentControls.Item($index); $key = if ([string]$control.Tag) { [string]$control.Tag } else { [string]$control.Title }; $property = $values.PSObject.Properties[$key]; if ($null -ne $property) { $control.Range.Text = [string]$property.Value; $filled++ } }; $document.Save(); Output @{ saved = $true; operation = $Operation; filled = $filled } }
      elseif ($Operation -eq 'updateFields') { $updated = $document.Fields.Update(); $document.Save(); Output @{ saved = $true; operation = $Operation; updated = [int]$updated } }
      elseif ($Operation -eq 'manageBookmarks') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'add') { $bookmarkName = [string](Get-RequiredParam 'name'); $bookmark = $document.Bookmarks.Add($bookmarkName, (Office-Range $document)); $document.Save(); Output @{ saved = $true; operation = $mode; name = $bookmarkName } } elseif ($mode -eq 'update') { $bookmarkName = [string](Get-RequiredParam 'name'); $bookmark = $document.Bookmarks.Item($bookmarkName); $bookmark.Range.Text = [string](Get-RequiredParam 'text'); $document.Bookmarks.Add($bookmarkName, $bookmark.Range) | Out-Null; $document.Save(); Output @{ saved = $true; operation = $mode; name = $bookmarkName } } elseif ($mode -eq 'delete') { $bookmarkName = [string](Get-RequiredParam 'name'); $document.Bookmarks.Item($bookmarkName).Delete(); $document.Save(); Output @{ saved = $true; operation = $mode; name = $bookmarkName } } else { Fail "Unsupported bookmark operation '$mode'." } }
      elseif ($Operation -eq 'manageHyperlinks') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'add') { $link = $document.Hyperlinks.Add((Office-Range $document), [string](Get-RequiredParam 'address'), $null, $null, [string](Get-RequiredParam 'text')); $document.Save(); Output @{ saved = $true; operation = $mode; address = [string]$link.Address } } elseif ($mode -eq 'update' -or $mode -eq 'delete') { $index = [int](Get-RequiredParam 'index') + 1; $link = $document.Hyperlinks.Item($index); if ($mode -eq 'delete') { $link.Delete() } else { $link.Address = [string](Get-RequiredParam 'address') }; $document.Save(); Output @{ saved = $true; operation = $mode; index = $index - 1 } } else { Fail "Unsupported hyperlink operation '$mode'." } }
      elseif ($Operation -eq 'manageLists') { $mode = [string](Get-RequiredParam 'operation'); $range = Office-Range $document; if ($mode -eq 'apply') { $listType = if ($null -eq $request.params.listType) { 'bullet' } else { [string]$request.params.listType }; if ($listType -eq 'number') { $range.ListFormat.ApplyNumberDefault() } elseif ($listType -eq 'bullet') { $range.ListFormat.ApplyBulletDefault() } else { Fail "Unsupported list type '$listType'." }; $level = if ($null -eq $request.params.level) { 1 } else { [int]$request.params.level }; $range.ListFormat.ListLevelNumber = $level; $document.Save(); Output @{ saved = $true; operation = $mode; listType = $listType; level = $level } } elseif ($mode -eq 'clear') { $range.ListFormat.RemoveNumbers(); $document.Save(); Output @{ saved = $true; operation = $mode } } else { Fail "Unsupported list operation '$mode'." } }
      elseif ($Operation -eq 'manageFootnotes') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'add') { $note = $document.Footnotes.Add((Office-Range $document), $null, [string](Get-RequiredParam 'text')); $document.Save(); Output @{ saved = $true; operation = $mode; index = $document.Footnotes.Count - 1 } } elseif ($mode -eq 'delete') { $document.Footnotes.Item(([int](Get-RequiredParam 'index')) + 1).Delete(); $document.Save(); Output @{ saved = $true; operation = $mode } } else { Fail "Unsupported footnote operation '$mode'." } }
      else { Fail "The docs write operation '$Operation' requires a supported Word backend operation." }
      $document.Save(); Output @{ saved = $true; operation = $Operation }
    }
    if ($Format -eq 'excel') {
      if ($Operation -eq 'addSheet') { $name = [string](Get-RequiredParam 'sheetName'); $newSheet = $document.Worksheets.Add(); $newSheet.Name = $name; $document.Save(); Output @{ saved = $true; sheet = $name } }
      if ($Operation -eq 'deleteSheet') { $sheetName = [string](Get-RequiredParam 'sheet'); $document.Worksheets.Item($sheetName).Delete(); $document.Save(); Output @{ saved = $true; sheet = $sheetName } }
      if ($Operation -eq 'manageNamedRange') { $mode = [string](Get-RequiredParam 'operation'); $name = [string](Get-RequiredParam 'name'); if ($mode -eq 'create') { $named = $document.Names.Add($name, [string](Get-RequiredParam 'formula')); $document.Save(); Output @{ saved = $true; operation = $mode; name = $name; formula = [string]$named.RefersTo } } elseif ($mode -eq 'update') { $document.Names.Item($name).Delete(); $named = $document.Names.Add($name, [string](Get-RequiredParam 'formula')); $document.Save(); Output @{ saved = $true; operation = $mode; name = $name; formula = [string]$named.RefersTo } } elseif ($mode -eq 'delete') { $document.Names.Item($name).Delete(); $document.Save(); Output @{ saved = $true; operation = $mode; name = $name } } else { Fail "Unsupported named range operation '$mode'." } }
      if ($Operation -eq 'setDataValidation') { $sheet = if ($null -eq (Get-OptionalParam 'sheet')) { $document.Worksheets.Item(1) } else { $document.Worksheets.Item([string](Get-OptionalParam 'sheet')) }; $range = $sheet.Range([string](Get-RequiredParam 'range')); $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'clear') { $range.Validation.Delete() } elseif ($mode -eq 'set') { $range.Validation.Delete(); $type = if ($null -eq $request.params.options.type) { 3 } else { [int]$request.params.options.type }; $operator = if ($null -eq $request.params.options.operator) { 1 } else { [int]$request.params.options.operator }; $range.Validation.Add($type, $operator, 1, [string](Get-RequiredParam 'formula1'), [string](Get-OptionalParam 'formula2')) } else { Fail "Unsupported data validation operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; sheet = $sheet.Name; range = $range.Address() } }
      if ($Operation -eq 'managePivotTable') { $mode = [string](Get-RequiredParam 'operation'); $sheet = if ($null -eq (Get-OptionalParam 'sheet')) { $document.Worksheets.Item(1) } else { $document.Worksheets.Item([string](Get-OptionalParam 'sheet')) }; if ($mode -eq 'create') { $source = $sheet.Range([string](Get-RequiredParam 'sourceRange')); $destination = $sheet.Range([string](Get-RequiredParam 'range')); $name = [string](Get-RequiredParam 'tableName'); $cache = $document.PivotCaches().Create(1, $source); $pivot = $cache.CreatePivotTable($destination, $name); $document.Save(); Output @{ saved = $true; operation = $mode; name = $name } } elseif ($mode -eq 'refresh') { $pivot = $sheet.PivotTables().Item([string](Get-RequiredParam 'tableName')); $pivot.RefreshTable(); $document.Save(); Output @{ saved = $true; operation = $mode; name = [string]$pivot.Name } } elseif ($mode -eq 'delete') { $pivot = $sheet.PivotTables().Item([string](Get-RequiredParam 'tableName')); $pivot.TableRange2.Clear(); $document.Save(); Output @{ saved = $true; operation = $mode; name = [string]$request.params.tableName } } else { Fail "Unsupported pivot table operation '$mode'." } }
      if ($Operation -eq 'manageConditionalFormatting') { $sheet = Office-Sheet $document; $range = $sheet.Range([string](Get-RequiredParam 'range')); $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'clear') { $range.FormatConditions.Delete() } elseif ($mode -eq 'set') { $options = Get-OptionalParam 'options'; $type = if ($null -eq $options.type) { 2 } else { [int]$options.type }; $operator = if ($null -eq $options.operator) { 0 } else { [int]$options.operator }; $rule = if ($type -eq 1) { $range.FormatConditions.Add(1, $operator, [string](Get-RequiredParam 'formula1'), [string](Get-OptionalParam 'formula2')) } else { $range.FormatConditions.Add(2, 0, [string](Get-RequiredParam 'formula1')) }; if ($null -ne $options.fontColor) { $rule.Font.Color = [int]$options.fontColor }; if ($null -ne $options.fillColor) { $rule.Interior.Color = [int]$options.fillColor } } else { Fail "Unsupported conditional formatting operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; sheet = $sheet.Name; range = $range.Address() } }
      if ($Operation -eq 'manageSheetView') { $sheet = Office-Sheet $document; $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'freeze') { $range = $sheet.Range([string](Get-RequiredParam 'range')); $sheet.Activate(); $range.Select(); $document.Application.ActiveWindow.FreezePanes = $true } elseif ($mode -eq 'unfreeze') { $sheet.Activate(); $document.Application.ActiveWindow.FreezePanes = $false } elseif ($mode -eq 'set') { $sheet.Activate(); $options = Get-OptionalParam 'options'; if ($null -ne $options.zoom) { $document.Application.ActiveWindow.Zoom = [int]$options.zoom } } else { Fail "Unsupported worksheet view operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; sheet = $sheet.Name; freezePanes = [bool]$document.Application.ActiveWindow.FreezePanes; zoom = [int]$document.Application.ActiveWindow.Zoom } }
      if ($Operation -eq 'manageComments') { $sheet = Office-Sheet $document; $mode = [string](Get-RequiredParam 'operation'); $range = if ($null -eq $request.params.range) { $null } else { $sheet.Range([string]$request.params.range) }; if ($mode -eq 'add') { if ($null -eq $range) { throw 'A range is required to add a comment.' }; $comment = $range.AddComment([string](Get-RequiredParam 'text')); $document.Save(); Output @{ saved = $true; operation = $mode; address = $range.Address() } } elseif ($mode -eq 'update' -or $mode -eq 'delete') { if ($null -eq $range -or $null -eq $range.Comment) { throw 'The target cell does not contain a comment.' }; if ($mode -eq 'update') { $range.Comment.Text([string](Get-RequiredParam 'text')) } else { $range.Comment.Delete() }; $document.Save(); Output @{ saved = $true; operation = $mode; address = $range.Address() } } else { Fail "Unsupported comment operation '$mode'." } }
      if ($Operation -eq 'manageProtection') { $sheet = Office-Sheet $document; $mode = [string](Get-RequiredParam 'operation'); $kind = if ($null -eq $request.params.kind) { 'worksheet' } else { [string]$request.params.kind }; $password = if ($null -eq $request.params.password) { '' } else { [string]$request.params.password }; if ($kind -eq 'workbook') { if ($mode -eq 'protect') { $document.Protect($password) } elseif ($mode -eq 'unprotect') { $document.Unprotect($password) } else { Fail "Unsupported workbook protection operation '$mode'." }; $protected = [bool]$document.ProtectStructure } else { if ($mode -eq 'protect') { $sheet.Protect($password) } elseif ($mode -eq 'unprotect') { $sheet.Unprotect($password) } else { Fail "Unsupported worksheet protection operation '$mode'." }; $protected = [bool]$sheet.ProtectContents }; $document.Save(); Output @{ saved = $true; operation = $mode; kind = $kind; protected = $protected; sheet = $sheet.Name } }
      $sheet = if ($null -eq (Get-OptionalParam 'sheet')) { $document.Worksheets.Item(1) } else { $document.Worksheets.Item([string](Get-OptionalParam 'sheet')) }; $range = $sheet.Range([string](Get-RequiredParam 'range'))
      if ($Operation -eq 'clearRange') { $range.Clear() | Out-Null } elseif ($Operation -eq 'writeRange') { $value = Get-OptionalParam 'values'; if ($null -eq $value) { $value = Get-RequiredParam 'content' }; $range.Value2 = $value } elseif ($Operation -eq 'recalculate') { $document.RefreshAll(); $app.CalculateFull() } else { Fail "The excel write operation '$Operation' requires a supported Excel backend operation." }
      $document.Save(); Output @{ saved = $true; operation = $Operation }
    }
    if ($Format -eq 'pptx') {
      if ($Operation -eq 'addSlide') { $options = Get-OptionalParam 'options'; $layout = if ($null -eq $options -or $null -eq $options.layout) { 12 } else { [int]$options.layout }; $position = if ($null -eq $request.params.position) { $document.Slides.Count } else { [int]$request.params.position }; if ($position -lt 0 -or $position -gt $document.Slides.Count) { Fail 'The destination slide index is invalid.' }; $slide = $document.Slides.Add($position + 1, $layout); $document.Save(); Output @{ saved = $true; slide = $slide.SlideIndex - 1; layout = $layout } }
      if ($Operation -eq 'deleteSlide') { $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1).Delete(); $document.Save(); Output @{ saved = $true } }
      if ($Operation -eq 'setNotes') { $slide = $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1); $slide.NotesPage.Shapes.Placeholders.Item(2).TextFrame.TextRange.Text = [string](Get-RequiredParam 'content'); $document.Save(); Output @{ saved = $true } }
      if ($Operation -eq 'duplicateSlide') { $slide = $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1); $copy = $slide.Duplicate(); if ($null -ne $request.params.position) { $copy.MoveTo(([int]$request.params.position) + 1) }; $document.Save(); Output @{ saved = $true; operation = $Operation; slide = $copy.SlideIndex - 1 } }
      if ($Operation -eq 'importSlides') { $sourceApp = New-Object -ComObject PowerPoint.Application; $source = $null; try { $source = $sourceApp.Presentations.Open([string](Get-RequiredParam 'sourcePath'), $true, $true, $false); $imported = 0; for ($index = 1; $index -le $source.Slides.Count; $index++) { $source.Slides.Item($index).Copy(); $document.Slides.Paste($document.Slides.Count + 1) | Out-Null; $imported++ }; $document.Save(); Output @{ saved = $true; operation = $Operation; imported = $imported } } finally { if ($null -ne $source) { $source.Close() }; if ($null -ne $sourceApp) { $sourceApp.Quit() }; Release-Com $source; Release-Com $sourceApp } }
      if ($Operation -eq 'arrangeElements' -and [string]$request.params.operation -eq 'group') { $slide = $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1); $ids = [object[]](Get-RequiredParam 'elementIds'); if ($ids.Count -lt 2) { Fail 'Grouping requires at least two element ids.' }; $group = $slide.Shapes.Range($ids).Group(); $document.Save(); Output @{ saved = $true; operation = 'group'; elementId = [string]$group.Name } }
      if ($Operation -eq 'arrangeElements' -and ([string]$request.params.operation -eq 'distributeHorizontal' -or [string]$request.params.operation -eq 'distributeVertical')) { $slide = $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1); $ids = @((Get-RequiredParam 'elementIds')); if ($ids.Count -lt 3) { Fail 'Distribution requires at least three element ids.' }; $shapes = @($ids | ForEach-Object { $slide.Shapes.Item([string]$_) } | Sort-Object $(if ([string]$request.params.operation -eq 'distributeHorizontal') { 'Left' } else { 'Top' })); $horizontal = [string]$request.params.operation -eq 'distributeHorizontal'; $first = $shapes[0]; $last = $shapes[$shapes.Count - 1]; $span = if ($horizontal) { ($last.Left + $last.Width) - $first.Left } else { ($last.Top + $last.Height) - $first.Top }; $size = if ($horizontal) { ($shapes | Measure-Object -Property Width -Sum).Sum } else { ($shapes | Measure-Object -Property Height -Sum).Sum }; $gap = ($span - $size) / ($shapes.Count - 1); $cursor = if ($horizontal) { $first.Left } else { $first.Top }; foreach ($shape in $shapes) { if ($horizontal) { $shape.Left = $cursor; $cursor += $shape.Width + $gap } else { $shape.Top = $cursor; $cursor += $shape.Height + $gap } }; $document.Save(); Output @{ saved = $true; operation = [string]$request.params.operation; slide = [int]$request.params.slide } }
      if ($Operation -eq 'arrangeElements') { $slide = $document.Slides.Item(([int](Get-RequiredParam 'slide')) + 1); $ids = @((Get-RequiredParam 'elementIds')); if ($ids.Count -eq 0) { Fail 'arrangeElements requires at least one element id.' }; $shapes = @($ids | ForEach-Object { $slide.Shapes.Item([string]$_) }); $mode = [string](Get-RequiredParam 'operation'); if ($mode -eq 'front') { $shapes | ForEach-Object { $_.ZOrder(0) } } elseif ($mode -eq 'back') { $shapes | ForEach-Object { $_.ZOrder(1) } } elseif ($mode -eq 'left' -or $mode -eq 'right' -or $mode -eq 'top' -or $mode -eq 'bottom' -or $mode -eq 'center' -or $mode -eq 'middle') { $left = ($shapes | Measure-Object -Property Left -Minimum).Minimum; $top = ($shapes | Measure-Object -Property Top -Minimum).Minimum; $right = ($shapes | ForEach-Object { $_.Left + $_.Width } | Measure-Object -Maximum).Maximum; $bottom = ($shapes | ForEach-Object { $_.Top + $_.Height } | Measure-Object -Maximum).Maximum; foreach ($shape in $shapes) { if ($mode -eq 'left') { $shape.Left = $left } elseif ($mode -eq 'right') { $shape.Left = $right - $shape.Width } elseif ($mode -eq 'top') { $shape.Top = $top } elseif ($mode -eq 'bottom') { $shape.Top = $bottom - $shape.Height } elseif ($mode -eq 'center') { $shape.Left = ($left + $right - $shape.Width) / 2 } else { $shape.Top = ($top + $bottom - $shape.Height) / 2 } } } else { Fail "Unsupported arrangement operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; slide = [int]$request.params.slide } }
      if ($Operation -eq 'manageMedia') { $mode = [string](Get-RequiredParam 'operation'); $slide = Office-Slide $document; if ($mode -eq 'insert') { $path = [string](Get-RequiredParam 'mediaPath'); $options = Get-OptionalParam 'options'; $left = if ($null -eq $options.left) { 0 } else { [float]$options.left }; $top = if ($null -eq $options.top) { 0 } else { [float]$options.top }; $width = if ($null -eq $options.width) { 320 } else { [float]$options.width }; $height = if ($null -eq $options.height) { 240 } else { [float]$options.height }; $shape = $slide.Shapes.AddPicture($path, $false, $true, $left, $top, $width, $height); $document.Save(); Output @{ saved = $true; operation = $mode; slide = $slide.SlideIndex - 1; elementId = [string]$shape.Name } } $shape = $slide.Shapes.Item([string](Get-RequiredParam 'elementId')); if ($mode -eq 'update') { $options = Get-OptionalParam 'options'; if ($null -ne $options.left) { $shape.Left = [float]$options.left }; if ($null -ne $options.top) { $shape.Top = [float]$options.top }; if ($null -ne $options.width) { $shape.Width = [float]$options.width }; if ($null -ne $options.height) { $shape.Height = [float]$options.height } } elseif ($mode -eq 'delete') { $shape.Delete() } else { Fail "Unsupported media operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; elementId = [string]$request.params.elementId } }
      if ($Operation -eq 'manageHyperlinks') { $mode = [string](Get-RequiredParam 'operation'); $slide = Office-Slide $document; $shape = $slide.Shapes.Item([string](Get-RequiredParam 'elementId')); if ($mode -eq 'set') { $shape.ActionSettings(1).Hyperlink.Address = [string](Get-RequiredParam 'address') } elseif ($mode -eq 'clear') { $shape.ActionSettings(1).Hyperlink.Delete() } else { Fail "Unsupported presentation hyperlink operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; elementId = [string]$request.params.elementId } }
      if ($Operation -eq 'manageTransitions') { $mode = [string](Get-RequiredParam 'operation'); $transition = (Office-Slide $document).SlideShowTransition; if ($mode -eq 'set') { if ($null -ne $request.params.effect) { $transition.EntryEffect = [int]$request.params.effect }; if ($null -ne $request.params.options.advanceOnClick) { $transition.AdvanceOnClick = [bool]$request.params.options.advanceOnClick }; if ($null -ne $request.params.options.advanceTime) { $transition.AdvanceTime = [double]$request.params.options.advanceTime } } elseif ($mode -eq 'clear') { $transition.EntryEffect = 0; $transition.AdvanceOnClick = $true; $transition.AdvanceTime = 0 } else { Fail "Unsupported transition operation '$mode'." }; $document.Save(); Output @{ saved = $true; operation = $mode; slide = [int]$request.params.slide } }
      if ($Operation -eq 'manageLayouts') { $mode = [string](Get-RequiredParam 'operation'); if ($mode -ne 'apply') { Fail "Unsupported layout operation '$mode'." }; $slide = Office-Slide $document; $layoutIndex = [int](Get-RequiredParam 'index') + 1; $layout = $document.SlideMaster.CustomLayouts.Item($layoutIndex); $slide.CustomLayout = $layout; $document.Save(); Output @{ saved = $true; operation = $mode; slide = $slide.SlideIndex - 1; layout = [string]$layout.Name } }
      if ($Operation -eq 'findReplace') { Output (Replace-PptxText $document) }
      if ($Operation -eq 'exportPdf') { $output = [string](Get-RequiredParam 'outputPath'); $document.SaveAs($output, 32); Output @{ path = $output; exported = $true } }
      Fail "The pptx write operation '$Operation' requires a supported PowerPoint backend operation."
    }
  } finally { Office-Close $Format $document $app }
}

function Pdf-ExtractLinks([string]$DocumentPath) {
  $xmlText = Run-External 'pdftohtml' @('-xml', '-stdout', '-hidden', $DocumentPath, '-')
  try { $xml = [xml]$xmlText } catch { throw 'The PDF link extractor returned invalid XML.' }
  $selected = if ($null -eq $request.params.pages) { $null } else { @($request.params.pages | ForEach-Object { [int]$_ }) }; $items = @(); $page = 0
  foreach ($node in $xml.SelectNodes('//page|//link')) { if ($node.Name -eq 'page') { $page = [int]$node.number - 1 } elseif ($null -eq $selected -or $selected -contains $page) { $items += [ordered]@{ page = $page; address = [string]$node.href; text = Bound-Text ([string]$node.'#text'); bounds = @{ x = [double]$node.xmin; y = [double]$node.ymin; width = [double]$node.xmax - [double]$node.xmin; height = [double]$node.ymax - [double]$node.ymin } } } }
  return $items
}
function Pdf-ExtractAnnotations([string]$DocumentPath) {
  $dump = Run-External 'pdftk' @($DocumentPath, 'dump_data_annots'); $items = @(); $current = $null
  foreach ($line in ($dump -split "`r?`n")) { if ($line -eq '---') { if ($null -ne $current) { $items += $current }; $current = [ordered]@{}; continue }; if ($line -match '^Annotation(\w+):\s*(.*)$') { if ($null -eq $current) { $current = [ordered]@{} }; $current[$matches[1]] = $matches[2] } }
  if ($null -ne $current) { $items += $current }; $selected = if ($null -eq $request.params.pages) { $null } else { @($request.params.pages | ForEach-Object { [int]$_ }) }; if ($null -eq $selected) { return $items }; return @($items | Where-Object { $null -eq $_.AnnotationPageNumber -or $selected -contains ([int]$_.AnnotationPageNumber - 1) })
}
function Pdf-ManageAttachments([string]$DocumentPath, [string]$mode) {
  if ($mode -eq 'list') { $output = Run-External 'pdfdetach' @('-list', $DocumentPath); return @{ operation = $mode; details = $output } }
  if ($mode -eq 'extract') { $directory = [string](Get-RequiredParam 'outputPath'); New-Item -ItemType Directory -Path $directory -Force | Out-Null; Run-External 'pdfdetach' @('-saveall', '-o', $directory, $DocumentPath) | Out-Null; return @{ operation = $mode; outputPath = $directory; files = @(Get-ChildItem -LiteralPath $directory -File | ForEach-Object FullName) } }
  $temporary = "$DocumentPath.$([guid]::NewGuid()).pdf"
  try { if ($mode -eq 'attach') { $source = [string](Get-RequiredParam 'sourcePath'); Run-External 'pdftk' @($DocumentPath, 'attach_files', $source, 'output', $temporary) | Out-Null } elseif ($mode -eq 'delete') { $name = [string](Get-RequiredParam 'name'); Run-External 'qpdf' @($DocumentPath, '--remove-attachment=' + $name, $temporary) | Out-Null } else { throw "Unsupported attachment operation '$mode'." }; Move-Item -LiteralPath $temporary -Destination $DocumentPath -Force; return @{ operation = $mode; updated = $true } } finally { Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue }
}
function New-PdfPageNumberStamp([int]$count, [string]$position) {
  $objects = @(); $kids = @(); for ($i = 1; $i -le $count; $i++) { $content = if ($position -eq 'top') { "BT /F1 10 Tf 280 770 Td ($i) Tj ET" } else { "BT /F1 10 Tf 280 20 Td ($i) Tj ET" }; $contentObject = $objects.Count + 4; $objects += "<< /Length $($content.Length) >>`nstream`n$content`nendstream"; $pageObject = $objects.Count + 4; $kids += "$pageObject 0 R"; $objects += "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents $contentObject 0 R /Resources << /Font << /F1 $($count * 2 + 3) 0 R >> >> >>" }; $objects = @('<< /Type /Catalog /Pages 2 0 R >>', "<< /Type /Pages /Kids [$($kids -join ' ')] /Count $count >>") + $objects + @('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); $builder = New-Object Text.StringBuilder; [void]$builder.AppendLine('%PDF-1.4'); $offsets = @(); for ($i = 0; $i -lt $objects.Count; $i++) { $offsets += $builder.Length; [void]$builder.AppendLine("$($i + 1) 0 obj"); [void]$builder.AppendLine($objects[$i]); [void]$builder.AppendLine('endobj') }; $xref = $builder.Length; [void]$builder.AppendLine('xref'); [void]$builder.AppendLine("0 $($objects.Count)"); [void]$builder.AppendLine('0000000000 65535 f '); foreach ($offset in $offsets) { [void]$builder.AppendLine(('{0:D10} 00000 n ' -f $offset)) }; [void]$builder.AppendLine('trailer'); [void]$builder.AppendLine("<< /Size $($objects.Count) /Root 1 0 R >>"); [void]$builder.AppendLine('startxref'); [void]$builder.AppendLine([string]$xref); [void]$builder.AppendLine('%%EOF'); $stamp = Join-Path ([IO.Path]::GetTempPath()) ("lotagate-page-numbers-" + [guid]::NewGuid().ToString() + '.pdf'); [IO.File]::WriteAllText($stamp, $builder.ToString(), [Text.Encoding]::ASCII); return $stamp
}
function Process-PdfExtended([string]$DocumentPath, [string]$Operation) {
  if ($Operation -eq 'extractLinks') { return @{ operation = $Operation; links = @(Pdf-ExtractLinks $DocumentPath) } }
  if ($Operation -eq 'extractAnnotations') { $pages = $request.params.pages; return @{ operation = $Operation; pages = $pages; annotations = @(Pdf-ExtractAnnotations $DocumentPath) } }
  if ($Operation -eq 'manageAttachments') { return Pdf-ManageAttachments $DocumentPath ([string](Get-RequiredParam 'operation')) }
  $output = [string](Get-RequiredParam 'outputPath'); if ([IO.Path]::GetExtension($output).ToLowerInvariant() -ne '.pdf') { throw 'The PDF output path must use the .pdf extension.' }; if (([IO.Path]::GetFullPath($output)) -eq ([IO.Path]::GetFullPath($DocumentPath))) { throw 'The PDF output path must be different from the input path.' }; if (Test-Path -LiteralPath $output) { throw 'The PDF output path already exists.' }; $temporary = "$output.$([guid]::NewGuid()).tmp.pdf"
  try {
    if ($Operation -eq 'flattenForms') { Run-External 'pdftk' @($DocumentPath, 'output', $temporary, 'flatten') | Out-Null }
    elseif ($Operation -eq 'optimize') { Run-External 'gswin64c' @('-sDEVICE=pdfwrite', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-sOutputFile=' + $temporary, $DocumentPath) | Out-Null }
    elseif ($Operation -eq 'addPageNumbers') { $position = if ($null -eq $request.params.options.position) { 'bottom' } else { [string]$request.params.options.position }; $stamp = New-PdfPageNumberStamp (Pdf-PageCount $DocumentPath) $position; try { Run-External 'pdftk' @($DocumentPath, 'stamp', $stamp, 'output', $temporary) | Out-Null } finally { Remove-Item -LiteralPath $stamp -Force -ErrorAction SilentlyContinue } }
    else { throw "Unsupported PDF operation '$Operation'." }
    Move-Item -LiteralPath $temporary -Destination $output -Force; return @{ operation = $Operation; path = $output; updated = $true }
  } finally { Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue }
}

try { $request = [Console]::In.ReadToEnd() | ConvertFrom-Json } catch { Fail 'The document backend received invalid JSON.' }
$action = [string]$request.action; $parts = $action.Split('.', 2); $format = $parts[0]; $operation = $parts[1]; $path = [string]$request.path
if ($format -notin @('pdf', 'pptx', 'excel', 'docs') -or [string]::IsNullOrWhiteSpace($operation)) { Fail 'The document backend received an invalid action.' }
Assert-Extension $path $format

if ($operation -eq 'create') { if ($format -eq 'pdf') { New-Pdf $path ([string](Get-OptionalParam 'title')); Output @{ created = $true; format = $format } }; Fail "Creating $format documents requires the corresponding Office application." }
if ($operation -eq 'validate') { if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { Fail 'The document does not exist.' }; $bytes = [IO.File]::ReadAllBytes($path); $valid = if ($format -eq 'pdf') { [Text.Encoding]::ASCII.GetString($bytes, 0, [Math]::Min(5, $bytes.Length)) -eq '%PDF-' } else { $bytes.Length -ge 2 -and $bytes[0] -eq 80 -and $bytes[1] -eq 75 }; if (-not $valid) { Fail 'The document signature is invalid.' }; Output @{ valid = $true; format = $format } }
if ($format -eq 'docs' -and $operation -eq 'readContent' -and [IO.Path]::GetExtension($path).ToLowerInvariant() -eq '.txt') { Output @{ format = 'docs'; content = [IO.File]::ReadAllText($path) } }
if ($format -eq 'pdf' -and $operation -eq 'inspect') { $info = Run-External 'pdfinfo' @($path); Output @{ format = 'pdf'; path = $path; info = $info } }
if ($format -eq 'pdf' -and ($operation -eq 'readText' -or $operation -eq 'extractTables')) { $text = Read-PdfText $path; Output @{ format = 'pdf'; text = $text; operation = $operation } }
if ($format -eq 'pdf' -and $operation -eq 'recognizeText') { $pages = @(Pdf-SelectedPages $path); $allText = New-Object Text.StringBuilder; $allLines = @(); $languageTag = ''; $temporaryFiles = @(); try { foreach ($page in $pages) { $prefix = Join-Path ([IO.Path]::GetTempPath()) ("lotagate-pdf-" + [guid]::NewGuid().ToString()); $imagePath = "$prefix.png"; Run-External 'pdftoppm' @('-png', '-singlefile', '-f', ([string]($page + 1)), '-l', ([string]($page + 1)), $path, $prefix) | Out-Null; $temporaryFiles += $imagePath; $ocr = Recognize-ImageText ([IO.File]::ReadAllBytes($imagePath)) ([string]$request.params.language); if ([string]::IsNullOrWhiteSpace($languageTag)) { $languageTag = [string]$ocr.language }; [void]$allText.AppendLine([string]$ocr.text); foreach ($line in @($ocr.lines)) { $allLines += [ordered]@{ page = $page; text = [string]$line.text; bounds = $line.bounds } } }; Output @{ format = 'pdf'; text = $allText.ToString().Trim(); language = $languageTag; lines = $allLines; pages = $pages } } finally { foreach ($temporaryFile in $temporaryFiles) { Remove-Item -LiteralPath $temporaryFile -Force -ErrorAction SilentlyContinue } } }
if ($format -eq 'pdf' -and $operation -eq 'search') { $query = [string](Get-RequiredParam 'query'); $maxResults = if ($null -eq $request.params.maxResults) { 100 } else { [Math]::Min([Math]::Max([int]$request.params.maxResults, 1), 1000) }; $text = Run-External 'pdftotext' @('-layout', $path, '-'); $pages = $text -split "`f"; $selected = $request.params.pages; $matches = @(); for ($page = 0; $page -lt $pages.Count -and $matches.Count -lt $maxResults; $page++) { if ($null -ne $selected -and @($selected).Count -gt 0 -and -not (@($selected | ForEach-Object { [int]$_ }) -contains $page)) { continue }; $lines = $pages[$page] -split "`r?`n"; for ($lineIndex = 0; $lineIndex -lt $lines.Count -and $matches.Count -lt $maxResults; $lineIndex++) { if ($lines[$lineIndex].IndexOf($query, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) { $matches += [ordered]@{ page = $page; line = $lineIndex; text = [string]$lines[$lineIndex].Trim() } } } }; Output @{ format = 'pdf'; query = $query; matches = $matches; truncated = $matches.Count -ge $maxResults } }
if ($format -eq 'pdf' -and $operation -eq 'extractImages') { Output (Extract-PdfImages $path) }
if ($format -eq 'pdf' -and $operation -eq 'manageBookmarks') { $bookmarkOperation = [string](Get-RequiredParam 'operation'); if ($bookmarkOperation -eq 'list') { Output @{ format = 'pdf'; operation = $bookmarkOperation; bookmarks = @(Read-PdfBookmarks $path) } }; $updated = Update-PdfBookmarks $path $bookmarkOperation; Output @{ format = 'pdf'; operation = $bookmarkOperation; bookmarks = $updated } }
if ($format -eq 'pdf' -and $operation -in @('extractLinks', 'extractAnnotations')) { Output (Process-PdfExtended $path $operation) }
if ($format -eq 'pdf' -and $operation -in @('manageAttachments', 'flattenForms', 'optimize', 'addPageNumbers')) { Output (Process-PdfExtended $path $operation) }
if ($format -eq 'pdf' -and $operation -eq 'render') { Output (Render-Pdf $path) }
if ($format -eq 'pdf' -and $operation -eq 'merge') { $inputs = $request.params.paths; if ($null -eq $inputs -or $inputs.Count -lt 1) { Fail 'pdf.merge requires at least one input document.' }; Run-External 'pdfunite' ([string[]]$inputs + @($path)) | Out-Null; Output @{ format = 'pdf'; path = $path; merged = $inputs.Count } }
if ($operation -eq 'inspect') { $item = Get-Item -LiteralPath $path; Output @{ format = $format; path = $path; sizeBytes = $item.Length; lastWriteTimeUtc = $item.LastWriteTimeUtc.ToString('o') } }

# Keep the extended Office surface behind one dispatch boundary.  The generic
# COM handler above remains the owner for the established operations; these
# branches only cover operations that need dedicated COM object models.
if ($format -eq 'docs' -and $operation -in @('manageRevisions', 'manageComments') -and [string]$request.params.operation -in @('list', 'status')) { Read-OfficeExtended $format $path $operation }
if ($format -eq 'excel' -and $operation -in @('manageTable', 'manageChart', 'filterRange') -and [string]$request.params.operation -in @('list', 'status')) { Read-OfficeExtended $format $path $operation }
if ($format -eq 'docs' -and $operation -in @('setSection', 'manageRevisions', 'manageComments', 'render', 'exportPdf')) { Write-OfficeExtended $format $path $operation }
if ($format -eq 'excel' -and $operation -in @('updateSheet', 'manageTable', 'manageChart', 'filterRange', 'formatRange', 'sortRange', 'editRows', 'editColumns', 'importCsv', 'exportCsv', 'render', 'exportPdf')) { Write-OfficeExtended $format $path $operation }
if ($format -eq 'pptx' -and $operation -in @('reorderSlides', 'setTheme', 'updateSlide', 'addElement', 'updateElement', 'deleteElement', 'render', 'exportPdf')) { Write-OfficeExtended $format $path $operation }
if ($operation -in @('readContent', 'readRange', 'readSlide', 'inspectStructure', 'readFormulas', 'extractText') -or ($operation -in @('manageTable', 'manageImage', 'manageNamedRange', 'managePivotTable', 'manageBookmarks', 'manageHyperlinks', 'manageLists', 'manageFootnotes', 'manageConditionalFormatting', 'manageSheetView', 'manageComments', 'manageProtection', 'manageMedia', 'manageTransitions', 'manageLayouts') -and [string]$request.params.operation -in @('list', 'status'))) { Read-Office $format $path $operation }
if ($operation -in @('insertContent', 'updateContent', 'deleteContent', 'findReplace', 'setStyles', 'setHeaderFooter', 'manageTable', 'manageImage', 'fillTemplate', 'updateFields', 'manageNamedRange', 'setDataValidation', 'managePivotTable', 'writeRange', 'clearRange', 'recalculate', 'addSheet', 'deleteSheet', 'addSlide', 'deleteSlide', 'duplicateSlide', 'importSlides', 'arrangeElements', 'setNotes', 'exportPdf', 'manageBookmarks', 'manageHyperlinks', 'manageLists', 'manageFootnotes', 'manageConditionalFormatting', 'manageSheetView', 'manageComments', 'manageProtection', 'manageMedia', 'manageTransitions', 'manageLayouts')) { Write-Office $format $path $operation }
if ($operation -eq 'save') { Output @{ saved = $true; path = $path } }
Fail "The document operation '$operation' is not supported by the configured Windows backend."
