export const ASSISTANT_DELTA_BATCH_WINDOW_MS = 32;
export const ASSISTANT_DELTA_BATCH_SIZE = 32;
export const SUMMARY_INPUT_WORD_LIMIT = 100;
export const SUMMARY_TITLE_WORD_LIMIT = 10;
export const SUMMARY_TITLE_CHARACTER_LIMIT = 120;
