import { Archive, Files, GitBranch, PanelRight, Pencil, Pin, PinOff, Terminal } from 'lucide-react';
import type { Task, Workspace } from '../../../../contracts/ipc/v1/workspace.js';
import { ActionMenu } from '../../../components/ActionMenu.js';
import { IconButton } from '../../../components/ui.js';
import { formatTextClamp } from '../../../utils/text.js';

export function ConversationHeader({ task, workspace, changesOpen, sourcesOpen, terminalOpen, gitOpen, onToggleChanges, onToggleSources, onToggleTerminal, onToggleGit, onRenameTask, onPinTask, onArchiveTask }: { task?: Task | undefined; workspace?: Workspace | undefined; changesOpen: boolean; sourcesOpen: boolean; terminalOpen: boolean; gitOpen: boolean; onToggleChanges: () => void; onToggleSources: () => void; onToggleTerminal: () => void; onToggleGit: () => void; onRenameTask: (task: Task) => void; onPinTask: (pinned: boolean) => void; onArchiveTask: () => void }) {
  const title = task?.title ?? workspace?.name ?? 'Agent Workspace';
  const items = task === undefined ? [] : [{ label: task.pinned ? 'Unpin session' : 'Pin session', icon: task.pinned ? PinOff : Pin, onSelect: () => onPinTask(!task.pinned) }, { label: 'Rename', icon: Pencil, onSelect: () => onRenameTask(task) }, { label: 'Archive session', icon: Archive, tone: 'danger' as const, onSelect: onArchiveTask }];
  return <header className="conversation-header"><div className="task-title"><strong title={title}>{formatTextClamp(45, title)}</strong>{task ? <ActionMenu ariaLabel={`Session actions for ${title}`} items={items} /> : null}</div><div className="conversation-header-actions"><IconButton icon={GitBranch} iconSize={17} className="conversation-panel-toggle" label={gitOpen ? 'Hide Git panel' : 'Show Git panel'} aria-pressed={gitOpen} onClick={onToggleGit} /><IconButton icon={Terminal} iconSize={17} className="conversation-panel-toggle" label={terminalOpen ? 'Hide terminal' : 'Show terminal'} aria-pressed={terminalOpen} onClick={onToggleTerminal} /><IconButton icon={Files} iconSize={17} className="conversation-panel-toggle" label={sourcesOpen ? 'Hide sources' : 'Show sources'} aria-pressed={sourcesOpen} onClick={onToggleSources} /><IconButton icon={PanelRight} iconSize={17} className="conversation-panel-toggle" label={changesOpen ? 'Hide changed files panel' : 'Show changed files panel'} aria-pressed={changesOpen} onClick={onToggleChanges} /></div></header>;
}
