export const RUNTIME_CONFIG_SEED = 'lotagate-desktop-runtime-config-v1';
export const RUNTIME_CONFIG_FILE = 'runtime.dat';
export const PACKAGED_RUNTIME_KEYS = new Set([
  'LOTAGATE_API_BASE_URL',
  'LOTAGATE_TRUSTED_ORIGIN',
  'LOTAGATE_REMOTE_SERVER_URL',
  'LOTAGATE_REMOTE_SERVER_GLOBAL_PREFIX',
  'LOTAGATE_REMOTE_SERVER_ENROLLMENT_TOKEN',
]);
