import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react';

export type Language = 'en' | 'vi';
export type MessageKey = 'checkingSession' | 'signInTitle' | 'signInCopy' | 'emailOrUsername' | 'password' | 'signIn' | 'signingIn' | 'sessionProtected' | 'apiUnavailable' | 'sessionExpired' | 'checkingForUpdates' | 'checkForUpdates' | 'updateAvailable' | 'updateRequired' | 'updateUpToDate' | 'updateUnavailable' | 'updateDownload' | 'updateInstall' | 'updateContinue' | 'updateDownloading' | 'updateReady' | 'updateCurrentVersion' | 'updateLatestVersion' | 'updateReleaseNotes' | 'updatePlatform' | 'updateCliVersion' | 'updateApplicationId' | 'updateElectronVersion' | 'updateNodeVersion' | 'updateChannel' | 'updateInstallMode' | 'updateError' | 'updateDisabled';
const messages: Record<Language, Record<MessageKey, string>> = {
  en: { checkingSession: 'Checking session', signInTitle: 'Sign in to continue', signInCopy: 'Connect your account to start working with LotaGate Agent.', emailOrUsername: 'Email or username', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in', sessionProtected: 'Your session is protected by the LotaGate API.', apiUnavailable: 'Unable to connect to the LotaGate API.', sessionExpired: 'Your session expired. Please sign in again.', checkingForUpdates: 'Checking for updates', checkForUpdates: 'Check for updates', updateAvailable: 'A new version is available', updateRequired: 'This update is required to continue', updateUpToDate: 'You are up to date', updateUnavailable: 'No compatible installer is available for this device.', updateDownload: 'Download update', updateInstall: 'Install and restart', updateContinue: 'Continue without updating', updateDownloading: 'Downloading update', updateReady: 'Update is ready to install', updateCurrentVersion: 'Current version', updateLatestVersion: 'Latest version', updateReleaseNotes: 'Release notes', updatePlatform: 'Platform', updateCliVersion: 'CLI version', updateApplicationId: 'Application ID', updateElectronVersion: 'Electron', updateNodeVersion: 'Node.js', updateChannel: 'Update channel', updateInstallMode: 'Installation mode', updateError: 'Update check failed', updateDisabled: 'Updates are disabled in development.' },
  vi: { checkingSession: 'Đang kiểm tra phiên', signInTitle: 'Đăng nhập để tiếp tục', signInCopy: 'Kết nối tài khoản để bắt đầu làm việc với LotaGate Agent.', emailOrUsername: 'Email hoặc tên đăng nhập', password: 'Mật khẩu', signIn: 'Đăng nhập', signingIn: 'Đang đăng nhập', sessionProtected: 'Phiên của bạn được bảo vệ bởi LotaGate API.', apiUnavailable: 'Không thể kết nối tới LotaGate API.', sessionExpired: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.', checkingForUpdates: 'Đang kiểm tra bản cập nhật', checkForUpdates: 'Kiểm tra bản cập nhật', updateAvailable: 'Đã có phiên bản mới', updateRequired: 'Bản cập nhật này bắt buộc để tiếp tục', updateUpToDate: 'Ứng dụng đang ở phiên bản mới nhất', updateUnavailable: 'Chưa có bộ cài tương thích với thiết bị này.', updateDownload: 'Tải bản cập nhật', updateInstall: 'Cài đặt và khởi động lại', updateContinue: 'Tiếp tục không cập nhật', updateDownloading: 'Đang tải bản cập nhật', updateReady: 'Bản cập nhật đã sẵn sàng để cài đặt', updateCurrentVersion: 'Phiên bản hiện tại', updateLatestVersion: 'Phiên bản mới nhất', updateReleaseNotes: 'Ghi chú phát hành', updatePlatform: 'Nền tảng', updateCliVersion: 'Phiên bản CLI', updateApplicationId: 'Mã ứng dụng', updateElectronVersion: 'Electron', updateNodeVersion: 'Node.js', updateChannel: 'Kênh cập nhật', updateInstallMode: 'Kiểu cài đặt', updateError: 'Kiểm tra cập nhật thất bại', updateDisabled: 'Bản cập nhật bị tắt trong môi trường phát triển.' },
};

interface LocaleContextValue { language: Language; setLanguage: (language: Language) => Promise<void>; t: (key: MessageKey) => string; }
const LocaleContext = createContext<LocaleContextValue>({ language: 'en', setLanguage: async () => undefined, t: key => messages.en[key] });

export function LocaleProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<Language>('en');
  useEffect(() => { void window.lotagate.settings.get().then(value => { const loaded = value['language']; if (loaded === 'en' || loaded === 'vi') setLanguageState(loaded); }).catch(() => undefined); }, []);
  const value = useMemo<LocaleContextValue>(() => ({ language, setLanguage: async next => { await window.lotagate.settings.update({ language: next }); setLanguageState(next); }, t: key => messages[language][key] }), [language]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale(): LocaleContextValue { return useContext(LocaleContext); }
