/**
 * Canonical labels for the built-in tools exposed by the Desktop agent.
 *
 * Tool ids are protocol values and must remain stable. These labels are a
 * presentation concern, so they are deliberately kept outside the protocol
 * and shared by the main process and renderer wherever tool activity is shown.
 */
export const BUILTIN_TOOL_DISPLAY_NAMES = {
  'filesystem.read': 'Read file',
  'filesystem.list': 'List files',
  'filesystem.write': 'Write file',
  'filesystem.exists': 'Check file',
  'shell.exec': 'Run command',
  'skill.list': 'List skills',
  'skill.load': 'Load skill',
  'agent.spawn': 'Start subagent',
  'agent.wait': 'Wait for subagent',
  'agent.cancel': 'Cancel subagent',
  'work_plan.update': 'Update work plan',
  'browser.navigate': 'Open webpage',
  'browser.newTab': 'Open new tab',
  'browser.closeTab': 'Close browser tab',
  'browser.selectTab': 'Switch browser tab',
  'browser.inspect': 'Inspect webpage',
  'browser.inspectElement': 'Inspect webpage element',
  'browser.extractTable': 'Extract webpage table',
  'browser.drag': 'Drag webpage element',
  'browser.listFrames': 'List webpage frames',
  'browser.exportPdf': 'Export webpage PDF',
  'browser.console': 'Read browser console',
  'browser.network': 'Inspect network requests',
  'browser.accessibility': 'Inspect accessibility tree',
  'browser.setViewport': 'Set responsive viewport',
  'browser.resetViewport': 'Reset browser viewport',
  'browser.screenshot': 'Capture screenshot',
  'browser.click': 'Click webpage element',
  'browser.focus': 'Focus webpage field',
  'browser.clear': 'Clear webpage field',
  'browser.hover': 'Hover webpage element',
  'browser.check': 'Set checkbox',
  'browser.select': 'Select option',
  'browser.readField': 'Read form field',
  'browser.type': 'Enter text',
  'browser.upload': 'Upload browser file',
  'browser.download': 'Download browser file',
  'browser.dialog': 'Handle browser dialog',
  'browser.press': 'Press key',
  'browser.scroll': 'Scroll webpage',
  'browser.back': 'Go back',
  'browser.forward': 'Go forward',
  'browser.reload': 'Reload webpage',
  'browser.waitFor': 'Wait for webpage',
  'browser.tabs': 'List browser tabs',
  'computer.listWindows': 'List application windows',
  'computer.inspect': 'Inspect application window',
  'computer.screenshot': 'Capture application window',
  'computer.readText': 'Read application text',
  'computer.readSelection': 'Read application selection',
  'computer.readGrid': 'Read application grid',
  'computer.selectText': 'Select application text',
  'computer.listDisplays': 'List displays',
  'computer.recognizeText': 'Recognize application text',
  'computer.focus': 'Focus application window',
  'computer.click': 'Click application control',
  'computer.type': 'Type into application',
  'computer.keypress': 'Press application key',
  'computer.scroll': 'Scroll application',
  'computer.drag': 'Drag application control',
  'computer.launch': 'Launch application',
  'computer.wait': 'Wait for application',
  'computer.move': 'Move application pointer',
  'computer.setValue': 'Set application value',
  'computer.invoke': 'Invoke application control',
  'computer.select': 'Select application control',
  'computer.setToggleState': 'Set toggle state',
  'computer.setExpandedState': 'Set expanded state',
  'computer.scrollIntoView': 'Scroll control into view',
  'computer.setWindowState': 'Set application window state',
  'computer.closeWindow': 'Close application window',
  'computer.readClipboard': 'Read clipboard',
  'computer.writeClipboard': 'Write clipboard',
  'computer.waitForState': 'Wait for control state',
  'computer.manageFileDialog': 'Manage file dialog',
  'pdf.open': 'Open PDF',
  'pdf.create': 'Create PDF',
  'pdf.inspect': 'Inspect PDF',
  'pdf.validate': 'Validate PDF',
  'pdf.readText': 'Read PDF text',
  'pdf.recognizeText': 'Recognize PDF text',
  'pdf.search': 'Search PDF',
  'pdf.extractImages': 'Extract PDF images',
  'pdf.manageBookmarks': 'Manage PDF bookmarks',
  'pdf.render': 'Render PDF',
  'pdf.extractTables': 'Extract PDF tables',
  'pdf.insertPages': 'Insert PDF pages',
  'pdf.deletePages': 'Delete PDF pages',
  'pdf.reorderPages': 'Reorder PDF pages',
  'pdf.rotatePages': 'Rotate PDF pages',
  'pdf.merge': 'Merge PDFs',
  'pdf.split': 'Split PDF',
  'pdf.addText': 'Add PDF text',
  'pdf.addImage': 'Add PDF image',
  'pdf.annotate': 'Annotate PDF',
  'pdf.readForm': 'Read PDF form',
  'pdf.fillForm': 'Fill PDF form',
  'pdf.redact': 'Redact PDF',
  'pdf.save': 'Save PDF',
  'pdf.close': 'Close PDF',
  'pdf.extractLinks': 'Extract PDF links',
  'pdf.extractAnnotations': 'Extract PDF annotations',
  'pdf.manageAttachments': 'Manage PDF attachments',
  'pdf.flattenForms': 'Flatten PDF forms',
  'pdf.optimize': 'Optimize PDF',
  'pdf.addPageNumbers': 'Add PDF page numbers',
  'pptx.open': 'Open presentation',
  'pptx.create': 'Create presentation',
  'pptx.inspect': 'Inspect presentation',
  'pptx.validate': 'Validate presentation',
  'pptx.readSlide': 'Read presentation slide',
  'pptx.duplicateSlide': 'Duplicate presentation slide',
  'pptx.importSlides': 'Import presentation slides',
  'pptx.arrangeElements': 'Arrange slide elements',
  'pptx.findReplace': 'Find and replace slide text',
  'pptx.addSlide': 'Add presentation slide',
  'pptx.deleteSlide': 'Delete presentation slide',
  'pptx.reorderSlides': 'Reorder presentation slides',
  'pptx.updateSlide': 'Update presentation slide',
  'pptx.addElement': 'Add slide element',
  'pptx.updateElement': 'Update slide element',
  'pptx.deleteElement': 'Delete slide element',
  'pptx.setTheme': 'Set presentation theme',
  'pptx.setNotes': 'Set speaker notes',
  'pptx.render': 'Render presentation',
  'pptx.exportPdf': 'Export presentation PDF',
  'pptx.extractText': 'Extract presentation text',
  'pptx.manageMedia': 'Manage presentation media',
  'pptx.manageHyperlinks': 'Manage presentation hyperlinks',
  'pptx.manageTransitions': 'Manage slide transitions',
  'pptx.manageLayouts': 'Manage slide layouts',
  'pptx.save': 'Save presentation',
  'pptx.close': 'Close presentation',
  'excel.open': 'Open workbook',
  'excel.create': 'Create workbook',
  'excel.inspect': 'Inspect workbook',
  'excel.validate': 'Validate workbook',
  'excel.readRange': 'Read spreadsheet range',
  'excel.find': 'Find in workbook',
  'excel.manageNamedRange': 'Manage named range',
  'excel.setDataValidation': 'Set data validation',
  'excel.managePivotTable': 'Manage pivot table',
  'excel.writeRange': 'Write spreadsheet range',
  'excel.clearRange': 'Clear spreadsheet range',
  'excel.addSheet': 'Add worksheet',
  'excel.updateSheet': 'Update worksheet',
  'excel.deleteSheet': 'Delete worksheet',
  'excel.editRows': 'Edit worksheet rows',
  'excel.editColumns': 'Edit worksheet columns',
  'excel.formatRange': 'Format spreadsheet range',
  'excel.manageTable': 'Manage spreadsheet table',
  'excel.manageChart': 'Manage spreadsheet chart',
  'excel.sortRange': 'Sort spreadsheet range',
  'excel.filterRange': 'Filter spreadsheet range',
  'excel.recalculate': 'Recalculate workbook',
  'excel.render': 'Render worksheet',
  'excel.importCsv': 'Import CSV',
  'excel.exportCsv': 'Export CSV',
  'excel.exportPdf': 'Export workbook PDF',
  'excel.save': 'Save workbook',
  'excel.close': 'Close workbook',
  'excel.readFormulas': 'Read workbook formulas',
  'excel.manageConditionalFormatting': 'Manage conditional formatting',
  'excel.manageSheetView': 'Manage worksheet view',
  'excel.manageComments': 'Manage workbook comments',
  'excel.manageProtection': 'Manage workbook protection',
  'docs.open': 'Open document',
  'docs.create': 'Create document',
  'docs.inspect': 'Inspect document',
  'docs.validate': 'Validate document',
  'docs.readContent': 'Read document content',
  'docs.manageTable': 'Manage document table',
  'docs.manageImage': 'Manage document image',
  'docs.fillTemplate': 'Fill document template',
  'docs.updateFields': 'Update document fields',
  'docs.insertContent': 'Insert document content',
  'docs.updateContent': 'Update document content',
  'docs.deleteContent': 'Delete document content',
  'docs.findReplace': 'Find and replace document text',
  'docs.setStyles': 'Set document styles',
  'docs.setSection': 'Set document section',
  'docs.setHeaderFooter': 'Set document header/footer',
  'docs.manageComments': 'Manage document comments',
  'docs.manageRevisions': 'Manage document revisions',
  'docs.render': 'Render document',
  'docs.exportPdf': 'Export document PDF',
  'docs.save': 'Save document',
  'docs.close': 'Close document',
  'docs.inspectStructure': 'Inspect document structure',
  'docs.manageBookmarks': 'Manage document bookmarks',
  'docs.manageHyperlinks': 'Manage document hyperlinks',
  'docs.manageLists': 'Manage document lists',
  'docs.manageFootnotes': 'Manage document footnotes',
} as const;

export function formatToolDisplayName(toolName: unknown, displayName: unknown): string {
  const normalizedToolName = normalize(toolName);
  const suppliedDisplayName = normalize(displayName);
  const builtInDisplayName = normalizedToolName === undefined
    ? undefined
    : BUILTIN_TOOL_DISPLAY_NAMES[normalizedToolName as keyof typeof BUILTIN_TOOL_DISPLAY_NAMES];
  if (suppliedDisplayName !== undefined && suppliedDisplayName !== normalizedToolName) return suppliedDisplayName;
  if (builtInDisplayName !== undefined) return builtInDisplayName;
  if (normalizedToolName?.startsWith('mcp__')) {
    const separator = normalizedToolName.lastIndexOf('__');
    return humanizeToolName(separator >= 0 ? normalizedToolName.slice(separator + 2) : normalizedToolName);
  }
  if (suppliedDisplayName !== undefined) return suppliedDisplayName;
  return normalizedToolName === undefined ? 'Tool' : humanizeToolName(normalizedToolName);
}

function normalize(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim();
  return normalized.length === 0 ? undefined : normalized;
}

function humanizeToolName(value: string): string {
  return value
    .replace(/[_\-.]+/gu, ' ')
    .replace(/([a-z])([A-Z])/gu, '$1 $2')
    .replace(/\s+/gu, ' ')
    .trim()
    .replace(/\b\w/gu, character => character.toUpperCase());
}
