import { useState } from 'react';
import { Button, Dropdown, Field, Modal, TextInput } from '../../components/ui.js';
import type { ExtensionScope } from './extension-command-client.js';
import { firstValidationError, validateExtensionName, validateExtensionSource, validateMcpFields } from './extensions-validation.js';
import { scopeOptions, type EditableExtensionKind, type ExtensionAddValue, type ValidationErrors } from './extensions-view-types.js';

export function ExtensionAddModal({ kind, busy, onClose, onSubmit }: { kind: EditableExtensionKind; busy: boolean; onClose: () => void; onSubmit: (value: ExtensionAddValue) => void }) {
  const [name, setName] = useState(''); const [source, setSource] = useState(''); const [scope, setScope] = useState<ExtensionScope>('user'); const [type, setType] = useState<'http' | 'sse'>('http'); const [url, setUrl] = useState(''); const [submitted, setSubmitted] = useState(false);
  const title = kind === 'mcp' ? 'Add MCP server' : kind === 'plugin' ? 'Add plugin' : 'Add skill';
  const errors: ValidationErrors = kind === 'mcp' ? { name: validateExtensionName(name), url: validateMcpFields(type, url)['url'] } : { source: validateExtensionSource(source) };
  const valid = firstValidationError(errors) === undefined; const submitLabel = kind === 'mcp' ? 'Add' : 'Install'; const busyLabel = kind === 'mcp' ? 'Adding…' : 'Installing…';
  const submit = () => { setSubmitted(true); if (!valid) return; if (kind === 'mcp') { onSubmit({ invocation: { actionId: 'mcp.add', positionals: [name.trim()], options: { type, url: url.trim(), scope } }, message: `Added MCP server ${name.trim()}` }); return; } onSubmit({ invocation: { actionId: 'plugin.install', positionals: [source.trim()], options: { scope } }, message: `Added ${kind} from ${source.trim()}` }); };
  return <Modal title={title} onClose={onClose}><div className="modal-form">{kind === 'mcp' ? <><Field label="Name" required error={submitted ? errors['name'] : undefined}><TextInput value={name} onChange={event => setName(event.target.value)} placeholder="my-mcp-server" autoFocus /></Field><Field label="Type"><Dropdown value={type} options={[{ value: 'http', label: 'HTTP' }, { value: 'sse', label: 'SSE' }]} onChange={value => setType(value as 'http' | 'sse')} /></Field><Field label="Scope"><Dropdown value={scope} options={scopeOptions} onChange={value => setScope(value as ExtensionScope)} /></Field><Field label="Server URL" required error={submitted ? errors['url'] : undefined}><TextInput value={url} onChange={event => setUrl(event.target.value)} placeholder="https://example.com/mcp" /></Field></> : <><Field label="Source" required error={submitted ? errors['source'] : undefined}><TextInput value={source} onChange={event => setSource(event.target.value)} placeholder="Local path, Git URL, or npm package" autoFocus /></Field><Field label="Scope"><Dropdown value={scope} options={scopeOptions} onChange={value => setScope(value as ExtensionScope)} /></Field></>}</div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="primary" disabled={busy || !valid} onClick={submit}>{busy ? busyLabel : submitLabel}</Button></div></Modal>;
}
