import { useState } from 'react';
import { Archive, Folder, Pencil, Pin, PinOff, Plus, Trash2 } from 'lucide-react';
import type { Task, Workspace } from '../../../../contracts/ipc/v1/workspace.js';
import { ActionMenu } from '../../../components/ActionMenu.js';
import { Icon, IconButton } from '../../../components/ui.js';
import { SessionTitle } from './SessionTitle.js';
import { sessionSlug } from '../conversation/task-title.js';

export interface WorkspaceGroupProps { workspace: Workspace; tasks: Task[]; activeTask?: Task | undefined; runningTaskIds: ReadonlySet<string>; unreadTaskIds: ReadonlySet<string>; onWorkspace: (workspace: Workspace) => void; onTask: (task: Task) => void; onNewChat: (workspace: Workspace) => void; onRename: (workspace: Workspace) => void; onRemove: (workspace: Workspace) => void; onArchive: (task: Task) => void; onPin: (task: Task, pinned: boolean) => void; onRenameTask: (task: Task) => void }

export function WorkspaceGroup({ workspace, tasks, activeTask, runningTaskIds, unreadTaskIds, onWorkspace, onTask, onNewChat, onRename, onRemove, onArchive, onPin, onRenameTask }: WorkspaceGroupProps) {
  const [showAllSessions, setShowAllSessions] = useState(false);
  const orderedTasks = [...tasks].sort((left, right) => Number(right.pinned) - Number(left.pinned) || right.updatedAt.localeCompare(left.updatedAt));
  const visibleTasks = showAllSessions ? orderedTasks : orderedTasks.slice(0, 5);
  const workspaceMenuHeader = <div className="action-menu-header-copy"><strong>{workspace.name}</strong><span>{tasks.length} chats · {tasks.filter(task => task.status === 'active').length} active</span><small>{workspace.rootPath}</small></div>;
  return <section className="workspace-group"><div className="workspace-row-shell"><button className="workspace-row" onClick={() => onWorkspace(workspace)}><Icon icon={Folder} size={15} /><span>{workspace.name}</span></button><IconButton icon={Plus} iconSize={14} className="workspace-new-chat" label={`New chat in ${workspace.name}`} onClick={() => onNewChat(workspace)} /><ActionMenu className="workspace-details-button" ariaLabel={`Workspace actions for ${workspace.name}`} header={workspaceMenuHeader} items={[{ label: 'Rename workspace', icon: Pencil, onSelect: () => onRename(workspace) }, { label: 'Remove workspace', icon: Trash2, tone: 'danger', onSelect: () => onRemove(workspace) }]} /></div><div className="session-list" aria-label={`${workspace.name} sessions`}>{visibleTasks.map(task => { const running = runningTaskIds.has(task.id) || task.status === 'active'; const unread = !running && unreadTaskIds.has(task.id); return <div key={task.id} className={`session-row-shell ${activeTask?.id === task.id ? 'active' : ''}`}><button className="session-row" onClick={() => onTask(task)}><SessionTitle title={sessionSlug(task)} />{running ? <span className="session-indicator session-indicator-running" role="status" aria-label="Agent is responding" /> : unread ? <span className="session-indicator session-indicator-unread" role="status" aria-label="New agent message" /> : null}{task.pinned ? <Pin className="session-pin" size={12} aria-label="Pinned session" /> : null}</button><ActionMenu ariaLabel={`Session actions for ${sessionSlug(task)}`} className="session-details-button" items={[{ label: task.pinned ? 'Unpin session' : 'Pin session', icon: task.pinned ? PinOff : Pin, onSelect: () => onPin(task, !task.pinned) }, { label: 'Rename', icon: Pencil, onSelect: () => onRenameTask(task) }, { label: 'Archive session', icon: Archive, tone: 'danger', onSelect: () => onArchive(task) }]} /></div>; })}{tasks.length > 5 ? <button className="session-show-more" onClick={() => setShowAllSessions(current => !current)}>{showAllSessions ? 'Show less' : 'Show more'}</button> : null}{tasks.length === 0 ? <span className="sidebar-empty">No sessions yet</span> : null}</div></section>;
}
