export const ACTIVITY_LOG_VERSION = 1;
export const DEFAULT_COMPACTION_BYTES = 1_024 * 1_024;
export const DEFAULT_COMPACTION_OPERATIONS = 4_096;
export const ATOMIC_RENAME_MAX_ATTEMPTS = 5;
export const ATOMIC_RENAME_INITIAL_BACKOFF_MS = 20;
